/* Ferie Quiz — spørgsmålsdata. Hver kategori har nem/mellem/svaer, 5 spørgsmål hver. */

const CATEGORIES = [
  { id: 'sommer',   name: 'Sommer & Ferie', emoji: '🏖️', color: '#FF6B57' },
  { id: 'mad',      name: 'Mad & Drikke',   emoji: '🍹', color: '#FFB238' },
  { id: 'film',     name: 'Film & TV',      emoji: '🎬', color: '#A66CFF' },
  { id: 'musik',    name: 'Musik',          emoji: '🎵', color: '#FF5DA2' },
  { id: 'geografi', name: 'Geografi & Verden', emoji: '🌍', color: '#2EC4B6' },
  { id: 'dyr',      name: 'Dyr & Natur',    emoji: '🐬', color: '#4CB963' },
  { id: 'sport',    name: 'Sport & Leg',    emoji: '🏐', color: '#3AA6FF' },
  { id: 'alment',   name: 'Alment & Sjov',  emoji: '🧠', color: '#FFD23F' },
  { id: 'influencer', name: 'Influencere & TikTok', emoji: '🤳', color: '#FF2E93' },
];

const QUESTIONS = {
  sommer: {
    nem: [
      { q: "Hvilken dansk ø kaldes 'Solskinsøen' pga. flest solskinstimer i landet?", options: ["Bornholm", "Møn", "Ærø", "Anholt"], correct: "Bornholm", fact: "Bornholm har op mod 1900 solskinstimer om året." },
      { q: "Ifølge den danske ferielov, hvor mange ugers betalt ferie har de fleste lønmodtagere ret til om året?", options: ["5 uger", "4 uger", "6 uger", "3 uger"], correct: "5 uger", fact: "Det svarer til 25 feriedage om året." },
      { q: "I hvilken by ligger Bakken, verdens ældste stadig fungerende forlystelsespark?", options: ["Klampenborg", "Roskilde", "Odense", "Aarhus"], correct: "Klampenborg", fact: "Bakken åbnede allerede i 1583." },
      { q: "I hvilket århundrede fik skolebørns sommerferie i Danmark for alvor sin faste form, bl.a. pga. landbrugets behov for arbejdskraft ved høst?", options: ["1800-tallet", "1900-tallet", "1700-tallet", "2000-tallet"], correct: "1800-tallet", fact: "Skolernes sommerferie skulle oprindeligt sikre arbejdskraft til høsten." },
      { q: "Cirka hvor mange af Danmarks øer er beboede?", options: ["Ca. 70", "Ca. 20", "Ca. 200", "Ca. 400"], correct: "Ca. 70", fact: "Kun omkring en tredjedel af Danmarks øer er beboede." },
    ],
    mellem: [
      { q: "Hvilket år blev Tivoli i København grundlagt?", options: ["1843", "1851", "1900", "1801"], correct: "1843", fact: "Tivoli var inspireret af Vauxhall Gardens i London." },
      { q: "Hvad hedder den spanske tradition i Pamplona, hvor man løber foran tyre gennem gaderne?", options: ["San Fermín", "La Tomatina", "Semana Santa", "Feria de Abril"], correct: "San Fermín", fact: "Festivalen er bedst kendt for tyreløbet 'encierro'." },
      { q: "Hvilket land har verdens længste kystlinje?", options: ["Canada", "Rusland", "Indonesien", "USA"], correct: "Canada", fact: "Canadas kystlinje er over 200.000 km lang, inkl. alle øer og fjorde." },
      { q: "Hvilken by var det klassiske slutmål for de fleste 'Grand Tour'-dannelsesrejser blandt velhavende unge europæere i 1700-tallet?", options: ["Rom", "Paris", "Wien", "Athen"], correct: "Rom", fact: "Rejsen kunne tage flere år og inkluderede ofte også Paris og Venedig." },
      { q: "Hvad kaldes det, når turisme presser lokalbefolkningen ud af boligmarkedet i populære feriebyer?", options: ["Overturisme", "Gentrificering", "Urbanisering", "Migration"], correct: "Overturisme", fact: "Byer som Venedig og Barcelona har indført afgifter for at dæmpe presset." },
    ],
    svaer: [
      { q: "Hvornår fik danske lønmodtagere for første gang lovfæstet ret til betalt ferie?", options: ["1938", "1919", "1948", "1960"], correct: "1938", fact: "Loven gav dengang ret til 2 ugers betalt ferie." },
      { q: "Hvad hedder den model, som forskeren Richard Butler i 1980 opstillede til at beskrive en turistdestinations udvikling fra opdagelse til forfald?", options: ["Turismens livscyklus (TALC)", "Bostons matrix", "Maslows behovspyramide", "Porters five forces"], correct: "Turismens livscyklus (TALC)", fact: "Modellen beskriver faser fra opdagelse til stagnation og forfald." },
      { q: "I hvilken by åbnede belgieren Gérard Blitz i 1950 den første Club Med-'landsby' — starten på det moderne all inclusive-koncept?", options: ["Alcúdia, Mallorca", "Cancún", "Ibiza By", "Benidorm"], correct: "Alcúdia, Mallorca", fact: "Konceptet startede som en simpel teltlejr for unge europæere." },
      { q: "Hvilket land har ifølge UNWTO modtaget flest internationale turistankomster hvert år i årtier, inkl. 2019?", options: ["Frankrig", "USA", "Spanien", "Kina"], correct: "Frankrig", fact: "Frankrig har toppet UNWTO's liste over flest internationale turister i årtier." },
      { q: "Hvilken by var det oprindelige mål for Thomas Cooks berømte togudflugt i 1841, som regnes for en af rejsebureau-branchens grundsten?", options: ["Loughborough", "London", "Paris", "Brighton"], correct: "Loughborough", fact: "Turen transporterede omkring 500 rejsende med tog fra Leicester." },
    ],
  },
  mad: {
    nem: [
      { q: "Hvilken by regnes for pizzaens fødested?", options: ["Napoli", "Rom", "Milano", "Firenze"], correct: "Napoli", fact: "Pizza Margherita blev opkaldt efter Italiens dronning i 1889." },
      { q: "Hvilket krydderi stammer fra støvfanget på en krokusblomst og er verdens dyreste pr. vægt?", options: ["Safran", "Vanilje", "Muskatnød", "Kardemomme"], correct: "Safran", fact: "Der skal ca. 150 blomster til for at lave 1 gram safran." },
      { q: "Hvad kaldes processen, hvor mælk omdannes til ost ved hjælp af enzymet løbe?", options: ["Koagulering", "Gæring", "Destillation", "Pasteurisering"], correct: "Koagulering", fact: "Løbe indeholder enzymet chymosin, som får mælken til at skille." },
      { q: "Hvilket land er ophavsland for retten paella?", options: ["Spanien", "Portugal", "Italien", "Marokko"], correct: "Spanien", fact: "Paella er opkaldt efter panden, den tilberedes i." },
      { q: "Hvad betyder det italienske udtryk 'al dente' bogstaveligt oversat?", options: ["Til tanden", "Meget blødt", "Perfekt", "Fast"], correct: "Til tanden", fact: "Udtrykket bruges specifikt om pasta, der stadig har en smule bid." },
    ],
    mellem: [
      { q: "Hvilken fransk by regnes for landets gastronomiske hovedstad og er hjemsted for kokken Paul Bocuse?", options: ["Lyon", "Paris", "Marseille", "Bordeaux"], correct: "Lyon", fact: "Byen er hjemsted for den legendariske kok Paul Bocuse." },
      { q: "Hvad kaldes en trænet japansk sushikok?", options: ["Itamae", "Wasabi", "Umami", "Nigiri"], correct: "Itamae", fact: "Det kan tage flere år at blive uddannet itamae." },
      { q: "Hvilken 'femte smag' blev identificeret af den japanske kemiker Kikunae Ikeda i 1908?", options: ["Umami", "Salt", "Bitter", "Metallisk"], correct: "Umami", fact: "Ordet betyder groft oversat 'lækker smag' på japansk." },
      { q: "Hvor mange stjerner er det maksimale antal, en restaurant kan opnå i Michelin-guiden?", options: ["3", "5", "4", "1"], correct: "3", fact: "Kun en lille brøkdel af verdens restauranter har opnået 3 stjerner." },
      { q: "Hvilken drue bruges traditionelt til champagne sammen med Chardonnay og Pinot Meunier?", options: ["Pinot Noir", "Merlot", "Cabernet Sauvignon", "Sauvignon Blanc"], correct: "Pinot Noir", fact: "Selvom druen er blå, presses den hurtigt, så vinen forbliver lys." },
    ],
    svaer: [
      { q: "Hvilken fransk by regnes for champagnens historiske hovedby og er hjemsted for producenter som Moët & Chandon?", options: ["Épernay", "Reims", "Dijon", "Nice"], correct: "Épernay", fact: "Byen kaldes ofte champagnens hovedstad." },
      { q: "Hvad hedder den kemiske reaktion mellem aminosyrer og sukkerarter, der giver stegt mad dens brune farve og smag, opkaldt efter en fransk kemiker?", options: ["Maillard-reaktionen", "Karamellisering", "Fotosyntese", "Oxidering"], correct: "Maillard-reaktionen", fact: "Reaktionen kræver typisk temperaturer over ca. 140°C." },
      { q: "I hvilket årti udviklede den franske kok Georges Pralus den moderne sous-vide-teknik?", options: ["1970'erne", "1950'erne", "1990'erne", "2000'erne"], correct: "1970'erne", fact: "Metoden bruges i dag også af hjemmekokke med vandbade." },
      { q: "Hvilken by huser Botín, som ifølge Guinness Rekordbog er verdens ældste stadig fungerende restaurant, grundlagt i 1725?", options: ["Madrid", "Rom", "Paris", "Lissabon"], correct: "Madrid", fact: "Restauranten nævnes bl.a. i Ernest Hemingways romaner." },
      { q: "Hvad hedder det franske klassifikationssystem fra 1855, der rangerer Bordeaux-vine efter kvalitet?", options: ["Bordeaux-klassifikationen af 1855", "Appellation d'Origine Contrôlée", "Grand Cru Classé", "Denominazione di Origine"], correct: "Bordeaux-klassifikationen af 1855", fact: "Kun fem vine opnåede oprindeligt den højeste rang, Premier Cru." },
    ],
  },
  film: {
    nem: [
      { q: "Hvem instruerede filmene 'Jaws', 'E.T.' og 'Jurassic Park'?", options: ["Steven Spielberg", "James Cameron", "George Lucas", "Christopher Nolan"], correct: "Steven Spielberg", fact: "Han er en af filmhistoriens mest indtjenende instruktører." },
      { q: "Hvilken skuespiller spillede Jack Dawson i 'Titanic' fra 1997?", options: ["Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Tom Cruise"], correct: "Leonardo DiCaprio", fact: "Filmen vandt hele 11 Oscars." },
      { q: "Hvad hedder troldmandsskolen i Harry Potter-universet?", options: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"], correct: "Hogwarts", fact: "Navnet betyder groft oversat 'vortesvin'." },
      { q: "Hvilket studie producerede 'Toy Story' i 1995, verdens første fuldt computeranimerede spillefilm?", options: ["Pixar", "DreamWorks", "Illumination", "Blue Sky Studios"], correct: "Pixar", fact: "Filmen krævede enorme mængder computertid at rendere." },
      { q: "Hvilken dansk instruktør vandt Oscar for bedste fremmedsprogede film med 'Babettes gæstebud' i 1988?", options: ["Gabriel Axel", "Lars von Trier", "Bille August", "Susanne Bier"], correct: "Gabriel Axel", fact: "Det var Danmarks første Oscar i denne kategori." },
    ],
    mellem: [
      { q: "Hvilken skuespiller har vundet Oscar for bedste mandlige hovedrolle flest gange (3 gange)?", options: ["Daniel Day-Lewis", "Jack Nicholson", "Tom Hanks", "Marlon Brando"], correct: "Daniel Day-Lewis", fact: "Han er kendt for ekstrem metode-skuespil." },
      { q: "Hvem grundlagde Dogme 95-bevægelsen sammen med Thomas Vinterberg?", options: ["Lars von Trier", "Nicolas Winding Refn", "Susanne Bier", "Bille August"], correct: "Lars von Trier", fact: "Dogme 95 krævede bl.a. håndholdt kamera og naturligt lys." },
      { q: "Hvilken film var i 1934 den første til at vinde de såkaldte 'Big Five' Oscars?", options: ["Det skete en nat", "Borte med blæsten", "Casablanca", "Rebecca"], correct: "Det skete en nat", fact: "Bedriften er kun gentaget to gange siden i Oscar-historien." },
      { q: "Hvilken bygning husede den allerførste Oscar-uddeling i 1929?", options: ["Hotel Roosevelt", "Dolby Theatre", "Kodak Theatre", "Shrine Auditorium"], correct: "Hotel Roosevelt", fact: "Kun omkring 270 gæster deltog i den 15 minutter lange ceremoni." },
      { q: "Hvem komponerede den ikoniske filmmusik til 'Star Wars', 'Jaws' og 'Jurassic Park'?", options: ["John Williams", "Hans Zimmer", "Ennio Morricone", "Danny Elfman"], correct: "John Williams", fact: "Han har komponeret musik til over 100 film." },
    ],
    svaer: [
      { q: "Hvilken film vandt det allerførste Oscar for bedste film i 1929?", options: ["Wings", "Sunrise", "The Jazz Singer", "Metropolis"], correct: "Wings", fact: "Filmen var en stumfilm om jagerpiloter i 1. verdenskrig." },
      { q: "Hvad hedder den franske filmbevægelse fra slutningen af 1950'erne, kendt for instruktører som Jean-Luc Godard og François Truffaut?", options: ["Nouvelle Vague", "Neorealisme", "Expressionisme", "Dogme 95"], correct: "Nouvelle Vague", fact: "Bevægelsen brød med traditionel filmteknik og -fortælling." },
      { q: "Hvilken skuespillerinde har modtaget flest Oscar-nomineringer for bedste kvindelige hovedrolle gennem tiden?", options: ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Cate Blanchett"], correct: "Meryl Streep", fact: "Hun har vundet prisen tre gange ud af sine mange nomineringer." },
      { q: "I hvilket år blev Cannes Film Festival første gang afholdt, efter at være udsat pga. krigen?", options: ["1946", "1932", "1955", "1939"], correct: "1946", fact: "Festivalen skulle egentlig være startet i 1939." },
      { q: "Hvilken italiensk instruktør står bag neorealisme-klassikeren 'Cykeltyven' (Ladri di biciclette)?", options: ["Vittorio De Sica", "Federico Fellini", "Michelangelo Antonioni", "Roberto Rossellini"], correct: "Vittorio De Sica", fact: "Filmen bruges ofte som skoleeksempel på italiensk neorealisme." },
    ],
  },
  musik: {
    nem: [
      { q: "Hvilken østrigsk komponist skrev 'Eine kleine Nachtmusik' og døde kun 35 år gammel?", options: ["Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Franz Schubert", "Joseph Haydn"], correct: "Wolfgang Amadeus Mozart", fact: "Han skrev over 600 værker i sit korte liv." },
      { q: "Hvilket svensk band skrev og sang 'Dancing Queen' og vandt Eurovision i 1974 med 'Waterloo'?", options: ["ABBA", "Roxette", "Ace of Base", "A-ha"], correct: "ABBA", fact: "Bandnavnet er dannet af medlemmernes forbogstaver." },
      { q: "Hvem er kendt som 'King of Pop'?", options: ["Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"], correct: "Michael Jackson", fact: "Han har solgt over 750 millioner plader på verdensplan." },
      { q: "Hvilken dansk sangerinde vandt Eurovision Song Contest for Danmark i 2013 med 'Only Teardrops'?", options: ["Emmelie de Forest", "Basim", "Rasmus Seebach", "MØ"], correct: "Emmelie de Forest", fact: "Sangen var Danmarks tredje Eurovision-sejr." },
      { q: "Hvor mange strenge har en klassisk (spansk) guitar normalt?", options: ["6", "4", "8", "12"], correct: "6", fact: "Nogle basguitarer har til sammenligning kun 4 strenge." },
    ],
    mellem: [
      { q: "Hvem komponerede balletten 'Svanesøen'?", options: ["Pjotr Tjajkovskij", "Sergej Prokofjev", "Igor Stravinskij", "Johannes Brahms"], correct: "Pjotr Tjajkovskij", fact: "Balletten blev første gang opført i Moskva i 1877." },
      { q: "Hvilket dansk symfoniorkester, grundlagt i 1448, regnes som et af verdens ældste?", options: ["Det Kongelige Kapel", "DR SymfoniOrkestret", "Aarhus Symfoniorkester", "Sjællands Symfoniorkester"], correct: "Det Kongelige Kapel", fact: "Orkestret spiller stadig faste forestillinger på Det Kongelige Teater." },
      { q: "Hvem opfandt saxofonen i 1840'erne?", options: ["Adolphe Sax", "Theobald Boehm", "Antonio Stradivari", "Johann Strauss"], correct: "Adolphe Sax", fact: "Han var oprindeligt fra Belgien, men arbejdede det meste af livet i Paris." },
      { q: "Hvilket album regnes ifølge de fleste opgørelser for verdens bedst sælgende nogensinde?", options: ["Thriller (Michael Jackson)", "Back in Black (AC/DC)", "The Dark Side of the Moon (Pink Floyd)", "Rumours (Fleetwood Mac)"], correct: "Thriller (Michael Jackson)", fact: "Albummet er solgt i over 70 millioner eksemplarer." },
      { q: "Hvilken komponist nåede ikke at færdiggøre operaen 'Turandot' før sin død i 1924?", options: ["Giacomo Puccini", "Giuseppe Verdi", "Gioachino Rossini", "Gaetano Donizetti"], correct: "Giacomo Puccini", fact: "Han nåede aldrig at høre sit værk blive opført." },
    ],
    svaer: [
      { q: "Hvem komponerede sin 'Requiem' på dødslejet i 1791, hvorefter en elev fuldførte værket?", options: ["Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Franz Schubert", "Antonio Salieri"], correct: "Wolfgang Amadeus Mozart", fact: "Han døde, mens han stadig arbejdede på værket, kun 35 år gammel." },
      { q: "Hvilken komponist var stort set stokdøv, da han skrev sin 9. symfoni?", options: ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johannes Brahms", "Franz Liszt"], correct: "Ludwig van Beethoven", fact: "Han skal angiveligt have brugt et savet klaver for bedre at mærke vibrationerne." },
      { q: "Hvad hedder det system, hvor alle 12 toner i den kromatiske skala bruges ligeværdigt, udviklet af Arnold Schönberg i starten af 1920'erne?", options: ["Tolvtonemusik (dodekafoni)", "Serialisme", "Atonalitet", "Minimalisme"], correct: "Tolvtonemusik (dodekafoni)", fact: "Teknikken bryder bevidst med traditionel toneart og harmonik." },
      { q: "I hvilken by havde Wolfgang Amadeus Mozart sin første ansættelse som hofkomponist?", options: ["Salzburg", "Wien", "Prag", "München"], correct: "Salzburg", fact: "Han blev senere uvenner med sin arbejdsgiver, ærkebiskoppen." },
      { q: "Hvilken russiske komponists ballet 'Le Sacre du Printemps' forårsagede optøjer ved premieren i Paris i 1913?", options: ["Igor Stravinskij", "Pjotr Tjajkovskij", "Sergej Prokofjev", "Dmitrij Sjostakovitj"], correct: "Igor Stravinskij", fact: "Publikum kom angiveligt i håndgemæng under premieren." },
    ],
  },
  geografi: {
    nem: [
      { q: "Hvad hedder verdens højeste bjerg målt fra havoverfladen?", options: ["Mount Everest", "K2", "Kangchenjunga", "Denali"], correct: "Mount Everest", fact: "Bjerget er 8.849 meter højt." },
      { q: "Hvilket land har flest indbyggere i verden i dag?", options: ["Indien", "Kina", "USA", "Indonesien"], correct: "Indien", fact: "Indien overhalede Kina som verdens mest folkerige land i 2023." },
      { q: "Hvad hedder verdens største varme ørken?", options: ["Sahara", "Gobi", "Kalahari", "Atacama"], correct: "Sahara", fact: "Sahara er næsten lige så stor som hele USA." },
      { q: "Hvilken by kaldes 'Den Evige Stad'?", options: ["Rom", "Athen", "Jerusalem", "Istanbul"], correct: "Rom", fact: "Tilnavnet hentyder til byens lange, uafbrudte historie." },
      { q: "Hvad hedder verdens mindste selvstændige land målt i areal?", options: ["Vatikanstaten", "Monaco", "San Marino", "Liechtenstein"], correct: "Vatikanstaten", fact: "Landet er kun ca. 0,44 kvadratkilometer stort." },
    ],
    mellem: [
      { q: "Hvilke to lande deler verdens længste landegrænse?", options: ["USA og Canada", "Rusland og Kina", "Kasakhstan og Rusland", "Chile og Argentina"], correct: "USA og Canada", fact: "Grænsen er over 8.800 km lang." },
      { q: "Hvilken by er verdens nordligste hovedstad i et selvstændigt land?", options: ["Reykjavik", "Oslo", "Helsinki", "Ottawa"], correct: "Reykjavik", fact: "Byen ligger så langt nordpå, at somrene har lyse nætter." },
      { q: "Hvilket land består af over 17.000 øer og er verdens største østat?", options: ["Indonesien", "Filippinerne", "Japan", "New Zealand"], correct: "Indonesien", fact: "Kun omkring 6.000 af landets øer er beboede." },
      { q: "Hvad hedder verdens dybeste sø, som indeholder cirka 20% af verdens ferske overfladevand?", options: ["Bajkalsøen", "Det Kaspiske Hav", "Tanganyikasøen", "Victoriasøen"], correct: "Bajkalsøen", fact: "Søen er over 1.600 meter dyb og millioner af år gammel." },
      { q: "Hvilket land har flest tidszoner, når man tæller alle oversøiske territorier med?", options: ["Frankrig", "Rusland", "USA", "Storbritannien"], correct: "Frankrig", fact: "De ekstra tidszoner skyldes bl.a. Fransk Polynesien og Guadeloupe." },
    ],
    svaer: [
      { q: "Hvad hedder verdens mest isolerede beboede øgruppe, hvor nærmeste nabo er over 2000 km væk?", options: ["Tristan da Cunha", "Påskeøen", "Socotra", "Saint Helena"], correct: "Tristan da Cunha", fact: "Nærmeste beboede nabo er Sankt Helena, ca. 2.400 km væk." },
      { q: "Hvilket land har historisk tre officielle hovedstæder — én for hver statsmagt?", options: ["Sydafrika", "Bolivia", "Sri Lanka", "Malaysia"], correct: "Sydafrika", fact: "Johannesburg er landets største by, men ikke en af hovedstæderne." },
      { q: "Hvilket stræde adskiller Rusland og USA og er kun ca. 4 km bredt mellem Diomedeøerne på det smalleste sted?", options: ["Beringstrædet", "Nordvestpassagen", "Malaccastrædet", "Dover-strædet"], correct: "Beringstrædet", fact: "Om vinteren kan strædet delvist fryse til." },
      { q: "Hvilket lille land grænser op til både Frankrig og Spanien uden selv at være medlem af EU?", options: ["Andorra", "Monaco", "San Marino", "Liechtenstein"], correct: "Andorra", fact: "Landet styres traditionelt af to statsoverhoveder — Frankrigs præsident og en spansk biskop." },
      { q: "Hvad hedder den zoogeografiske linje, opkaldt efter en britisk naturforsker, der adskiller Asiens og Australiens dyreliv?", options: ["Wallace-linjen", "Mercator-linjen", "Meridianen", "Richter-linjen"], correct: "Wallace-linjen", fact: "Linjen forklarer bl.a., hvorfor pungdyr findes øst for linjen, men ikke vest for." },
    ],
  },
  dyr: {
    nem: [
      { q: "Hvilket dyr er verdens største nulevende landdyr?", options: ["Elefant", "Flodhest", "Næsehorn", "Giraf"], correct: "Elefant", fact: "En voksen elefant kan veje op mod 6 tons." },
      { q: "Hvor mange ben har en edderkop?", options: ["8", "6", "10", "4"], correct: "8", fact: "Edderkopper er ikke insekter, men spindlere." },
      { q: "Hvilket havdyr er verdens største nulevende dyr overhovedet?", options: ["Blåhval", "Kaskelothval", "Hvid haj", "Spækhugger"], correct: "Blåhval", fact: "Blåhvalens hjerte alene kan veje omkring 180 kg." },
      { q: "Hvad hedder verdens højeste dyr?", options: ["Giraf", "Elefant", "Struds", "Kamel"], correct: "Giraf", fact: "En giraf kan blive op til 5-6 meter høj." },
      { q: "Hvilket dyr kan ændre farve for primært at kommunikere og kamuflere sig?", options: ["Kamæleon", "Frø", "Slange", "Firben"], correct: "Kamæleon", fact: "Kamæleoner skifter primært farve for at kommunikere, ikke kun for camouflage." },
    ],
    mellem: [
      { q: "Hvor mange hjerter har en blæksprutte?", options: ["3", "1", "2", "4"], correct: "3", fact: "To af hjerterne pumper blod til gællerne, det tredje til resten af kroppen." },
      { q: "Hvilket dyr sover med kun det halve af hjernen ad gangen?", options: ["Delfin", "Kat", "Hund", "Sæl"], correct: "Delfin", fact: "Det kaldes unihemisfærisk søvn." },
      { q: "Hvad kaldes fænomenet, hvor dyr som bjørne sænker stofskiftet markant og sover det meste af vinteren?", options: ["Hi/dvale", "Æstivation", "Diapause", "Torpor"], correct: "Hi/dvale", fact: "Under dvale sænkes puls og stofskifte markant." },
      { q: "Hvilken flyveudygtig fugl er verdens hurtigste løber blandt fugle?", options: ["Struds", "Emu", "Pingvin", "Kiwi"], correct: "Struds", fact: "En struds kan løbe op til 70 km/t." },
      { q: "Hvad er Danmarks nationalfugl?", options: ["Knopsvane", "Stork", "Ørn", "Ugle"], correct: "Knopsvane", fact: "Knopsvanen er en af Danmarks tungeste flyvende fugle." },
    ],
    svaer: [
      { q: "Cirka hvor mange 'hjerter' (aortabuer) har en regnorm?", options: ["10 (5 par)", "1", "3", "4 (2 par)"], correct: "10 (5 par)", fact: "De fungerer som pumper for regnormens blodkredsløb." },
      { q: "Hvilket dyr har det stærkeste målte bid blandt nulevende landdyr?", options: ["Saltvandskrokodille", "Løve", "Tiger", "Flodhest"], correct: "Saltvandskrokodille", fact: "Bidkraften er målt til over 3.700 psi." },
      { q: "Hvilken hvalart har det største kendte dyrehjerte, der kan veje op mod 180 kg?", options: ["Blåhval", "Kaskelothval", "Pukkelhval", "Finhval"], correct: "Blåhval", fact: "Hjertet er cirka på størrelse med en lille bil." },
      { q: "Hvad kaldes fænomenet, hvor visse dyrearter kan reproducere sig uden befrugtning fra hanner?", options: ["Partenogenese", "Metamorfose", "Symbiose", "Mitose"], correct: "Partenogenese", fact: "Det ses bl.a. hos visse haj-, firben- og insektarter." },
      { q: "Hvilket dyr har det største øje blandt alle kendte nulevende dyr, op til ca. 27 cm i diameter?", options: ["Kæmpeblæksprutte", "Blåhval", "Struds", "Hvid haj"], correct: "Kæmpeblæksprutte", fact: "Det enorme øje hjælper den med at spotte kaskelothvaler i mørket." },
    ],
  },
  sport: {
    nem: [
      { q: "Hvor mange spillere er der fra hvert hold på en fodboldbane samtidig (inkl. målmand)?", options: ["11", "9", "7", "13"], correct: "11", fact: "Det giver 22 spillere på banen i alt." },
      { q: "I hvilken by blev de første moderne olympiske lege afholdt i 1896?", options: ["Athen", "Paris", "London", "Rom"], correct: "Athen", fact: "Legene i 1896 havde deltagere fra 14 nationer." },
      { q: "Hvor mange ringe er der i det olympiske symbol?", options: ["5", "4", "6", "7"], correct: "5", fact: "Ringene symboliserer de fem beboede verdensdele." },
      { q: "Hvor langt er en maraton officielt?", options: ["42,195 km", "40 km", "45 km", "21,1 km"], correct: "42,195 km", fact: "Distancen stammer fra afstanden mellem Marathon og Athen." },
      { q: "Hvilket land har vundet flest VM-titler i mændenes fodbold?", options: ["Brasilien", "Tyskland", "Italien", "Argentina"], correct: "Brasilien", fact: "Brasilien er det eneste land, der har deltaget ved alle VM-slutrunder." },
    ],
    mellem: [
      { q: "I hvilket engelsk grevskab blev sporten badminton kodificeret i sin moderne form, opkaldt efter et gods?", options: ["Gloucestershire", "Yorkshire", "Kent", "Surrey"], correct: "Gloucestershire", fact: "Navnet stammer fra Badminton House, hvor sporten blev kodificeret." },
      { q: "Hvor mange spillere er der på hvert hold på banen samtidig i håndbold (inkl. målmand)?", options: ["7", "6", "8", "5"], correct: "7", fact: "Det er 6 markspillere og 1 målmand." },
      { q: "Hvilken by var vært for OL i 1980, som blev boykottet af en lang række vestlige lande pga. Sovjetunionens invasion af Afghanistan?", options: ["Moskva", "Los Angeles", "Montreal", "Seoul"], correct: "Moskva", fact: "Over 60 lande deltog i boykotten." },
      { q: "Hvad hedder den skotske vintersport, hvor man skyder polerede stensten hen mod et mål på is?", options: ["Curling", "Bandy", "Ishockey", "Skeleton"], correct: "Curling", fact: "Sporten stammer oprindeligt fra Skotland." },
      { q: "Hvor mange sæt skal en herresingle-spiller vinde for at vinde en kamp ved Wimbledon (best of hvor mange)?", options: ["3 ud af 5", "2 ud af 3", "4 ud af 7", "1 ud af 1"], correct: "3 ud af 5", fact: "Kvinderækken spiller til gengæld normalt bedst af 3 sæt." },
    ],
    svaer: [
      { q: "Hvornår vandt det danske herrehåndboldlandshold sit første OL-guld?", options: ["2016 (Rio)", "2012 (London)", "2008 (Beijing)", "2004 (Athen)"], correct: "2016 (Rio)", fact: "Holdet gentog bedriften ved både Tokyo 2020 og Paris 2024." },
      { q: "Hvilken by var oprindeligt tildelt værtskabet for OL 1940, men mistede det pga. 2. verdenskrig?", options: ["Tokyo", "Helsinki", "Berlin", "Rom"], correct: "Tokyo", fact: "Byen fik i stedet værtskabet for OL i 1964." },
      { q: "Hvor mange point er et field goal værd i basketball, hvis det skydes bagfra 3-punkts-linjen?", options: ["3", "2", "1", "4"], correct: "3", fact: "Reglen blev indført i NBA i 1979." },
      { q: "Hvilken sportsgren opfandt James Naismith i 1891 som en indendørs vinteraktivitet?", options: ["Basketball", "Volleyball", "Håndbold", "Badminton"], correct: "Basketball", fact: "Naismith brugte oprindeligt to frugtkurve som mål." },
      { q: "Hvor mange etaper består Tour de France normalt af?", options: ["21", "15", "25", "18"], correct: "21", fact: "Løbet strækker sig typisk over godt tre uger." },
    ],
  },
  alment: {
    nem: [
      { q: "Hvor mange knogler har et voksent menneske normalt?", options: ["206", "186", "226", "246"], correct: "206", fact: "Babyer fødes med omkring 300 knogler, som gror sammen." },
      { q: "Hvilket metal er flydende ved stuetemperatur?", options: ["Kviksølv", "Jern", "Guld", "Aluminium"], correct: "Kviksølv", fact: "Kviksølv er giftigt og bruges i dag langt sjældnere end tidligere." },
      { q: "Hvor mange planeter er der i vores solsystem, siden Pluto blev nedgraderet i 2006?", options: ["8", "9", "7", "10"], correct: "8", fact: "Pluto blev omklassificeret til en dværgplanet i 2006." },
      { q: "Hvilken dansk fysiker vandt Nobelprisen i fysik i 1922 for sit arbejde med atomets struktur?", options: ["Niels Bohr", "H.C. Ørsted", "Tycho Brahe", "Ole Rømer"], correct: "Niels Bohr", fact: "Han grundlagde senere Niels Bohr Institutet i København." },
      { q: "Hvad hedder den mindste enhed af et grundstof, der stadig har grundstoffets kemiske egenskaber?", options: ["Atom", "Molekyle", "Celle", "Elektron"], correct: "Atom", fact: "Ordet stammer fra græsk og betyder 'udelelig'." },
    ],
    mellem: [
      { q: "Hvad er hovedstaden i Australien (ikke Sydney)?", options: ["Canberra", "Sydney", "Melbourne", "Perth"], correct: "Canberra", fact: "Byen blev grundlagt som kompromis mellem Sydney og Melbourne." },
      { q: "Hvor mange hjerteslag har et menneske i gennemsnit per minut i hvile?", options: ["60-100", "20-40", "150-200", "250-300"], correct: "60-100", fact: "Under hård træning kan pulsen stige til det dobbelte eller mere." },
      { q: "Hvem opfandt World Wide Web i 1989?", options: ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Alan Turing"], correct: "Tim Berners-Lee", fact: "Han arbejdede dengang på forskningscentret CERN." },
      { q: "Hvilken dansk astronom opdagede i 1676, at lyset har en endelig hastighed?", options: ["Ole Rømer", "Tycho Brahe", "Niels Bohr", "H.C. Ørsted"], correct: "Ole Rømer", fact: "Han beregnede lysets hastighed ud fra observationer af Jupiters måner." },
      { q: "Hvad kaldes læren om jordens klimasystemer og atmosfæriske fænomener?", options: ["Meteorologi", "Geologi", "Astronomi", "Oceanografi"], correct: "Meteorologi", fact: "Moderne meteorologi bruger bl.a. satellitter og supercomputere." },
    ],
    svaer: [
      { q: "Hvilket år opdagede den danske fysiker H.C. Ørsted elektromagnetismen?", options: ["1820", "1800", "1850", "1900"], correct: "1820", fact: "Opdagelsen skete angiveligt ved et tilfælde under en forelæsning." },
      { q: "Hvad hedder den kognitive bias, hvor man overvurderer sandsynligheden for begivenheder, man let kan huske eksempler på?", options: ["Tilgængelighedsheuristik", "Bekræftelsesbias", "Ankereffekt", "Dunning-Kruger-effekten"], correct: "Tilgængelighedsheuristik", fact: "Bias'en får fx flyulykker til at føles hyppigere, end de statistisk er." },
      { q: "Hvor mange kromosomer har en normal menneskelig kropscelle?", options: ["46", "23", "44", "48"], correct: "46", fact: "Det svarer til 23 par, ét fra hver forælder." },
      { q: "Hvilken trykenhed er opkaldt efter den italienske fysiker Evangelista Torricelli?", options: ["Torr", "Pascal", "Bar", "Atmosfære"], correct: "Torr", fact: "760 torr svarer til normalt lufttryk ved havoverfladen." },
      { q: "Hvad hedder tallet, der angiver forholdet mellem en cirkels omkreds og diameter (ca. 3,14159)?", options: ["Pi (π)", "Phi (φ)", "Eulers tal (e)", "Tau (τ)"], correct: "Pi (π)", fact: "Tallet har uendeligt mange decimaler uden gentaget mønster." },
    ],
  },
  influencer: {
    nem: [
      { q: "Hvilket TV-program gjorde Silas Holst berømt som professionel danser?", options: ["Vild med Dans", "X Factor", "Voice", "Paradise Hotel"], correct: "Vild med Dans", fact: "Han har vundet programmet hele tre gange som professionel danser." },
      { q: "Hvilken dansk sanger er kendt for hittet 'Told You So' fra 2014?", options: ["Christopher", "Rasmus Seebach", "Basim", "Lukas Graham"], correct: "Christopher", fact: "Sangen nåede op som nummer 4 på den danske hitliste." },
      { q: "Hvilken by er TikTok-stjernen Zawadi Kristina kendt for at optræde i, i sine dansevideoer?", options: ["København", "Aarhus", "Odense", "Aalborg"], correct: "København", fact: "Hun er kendt for at blande afro-diasporisk mode med skandinavisk stil." },
      { q: "Hvilket verdenskendt undertøjsmærke har den danske model Josephine Skriver optrådt fast for siden 2015?", options: ["Victoria's Secret", "Calvin Klein", "H&M", "Chanel"], correct: "Victoria's Secret", fact: "Hun har gået med på catwalken ved deres store modeshow hvert år siden." },
      { q: "Hvad er TikTokeren Yespar især kendt for at lave videoer om?", options: ["Sjove sketches og udfordringer", "Nyhedsanalyser", "Madlavningstutorials", "Boganmeldelser"], correct: "Sjove sketches og udfordringer", fact: "Han slog for alvor igennem omkring 2020." },
    ],
    mellem: [
      { q: "Hvilket dansk realityprogram blev Gustav Salinas oprindeligt kendt fra som 18-årig i 2008?", options: ["Dagens Mand", "Paradise Hotel", "Ex on the Beach", "Bachelor"], correct: "Dagens Mand", fact: "I dag laver han i stedet indhold om træning og forretning." },
      { q: "Hvad hedder de to virksomheder, Gustav Salinas driver ved siden af sit indhold i dag?", options: ["FitnessNu og Salinas Slik", "Matas og Netto", "Zalando og H&M", "Lego og Bestseller"], correct: "FitnessNu og Salinas Slik", fact: "Den ene handler om træning, den anden om slik." },
      { q: "Hvad er Anders Hemmingsen især kendt for at drive på Instagram?", options: ["Danmarks mest fulgte meme-side", "En nyhedskanal", "En boligblog", "En rejseblog"], correct: "Danmarks mest fulgte meme-side", fact: "Siden deler humoristisk indhold, som ofte bliver delt videre af følgerne." },
      { q: "Hvilke to modemærker har TikTokeren Zawadi Kristina bl.a. lavet reklamesamarbejder med?", options: ["Zalando og H&M", "Nike og Adidas", "Lego og Netto", "Apple og Samsung"], correct: "Zalando og H&M", fact: "Den slags samarbejder er en vigtig indtægtskilde for mange influencere." },
      { q: "Hvilken hæderspris fik Christopher i 2013 for sin store tilstedeværelse på det sociale medie Instagram?", options: ["Årets Instagrammer", "Årets YouTuber", "Årets Podcaster", "Årets Blogger"], correct: "Årets Instagrammer", fact: "Prisen blev uddelt af The Voice." },
    ],
    svaer: [
      { q: "I hvilket år blev Silas Holst den første professionelle danser i 'Vild med dans' til at vinde med en partner af samme køn?", options: ["2019", "2015", "2021", "2011"], correct: "2019", fact: "Han vandt sammen med skuespiller Jakob Fauerby." },
      { q: "Hvor mange gange har Silas Holst i alt vundet 'Vild med dans' som professionel danser?", options: ["3 gange", "1 gang", "5 gange", "2 gange"], correct: "3 gange", fact: "Det gør ham til en af de mest vindende professionelle dansere i programmets historie." },
      { q: "Hvad hedder Gustav Salinas' ægtefælle, som ofte optræder i hans indhold?", options: ["Mulle", "Frederik", "Kevin", "Anders"], correct: "Mulle", fact: "Han deler ofte glimt af deres liv sammen med følgerne." },
      { q: "Hvilket bureau er TikTokeren Yespar tilknyttet for professionelle samarbejder?", options: ["Eighteen Agency", "United Influencers", "Talent Nation", "Zenith Media"], correct: "Eighteen Agency", fact: "Bureauer som dette matcher influencere med brands, der ønsker reklamesamarbejder." },
      { q: "I hvilket årti fik Christopher sit store gennembrud som popsanger i Danmark?", options: ["2010'erne", "1990'erne", "2000'erne", "2020'erne"], correct: "2010'erne", fact: "Albummet 'Told You So' udkom i 2014." },
    ],
  },
};
