/* Ferie Quiz — spørgsmålsdata. Hver kategori har nem/mellem/svaer. */

const CATEGORIES = [
  { id: 'sommer',   name: 'Sommer & Ferie', emoji: '🏖️', color: '#FF6B57' },
  { id: 'mad',      name: 'Mad & Drikke',   emoji: '🍹', color: '#FFB238' },
  { id: 'film',     name: 'Film & TV',      emoji: '🎬', color: '#A66CFF' },
  { id: 'musik',    name: 'Musik',          emoji: '🎵', color: '#FF5DA2' },
  { id: 'geografi', name: 'Geografi & Verden', emoji: '🌍', color: '#2EC4B6' },
  { id: 'dyr',      name: 'Dyr & Natur',    emoji: '🐬', color: '#4CB963' },
  { id: 'sport',    name: 'Sport & Leg',    emoji: '🏐', color: '#3AA6FF' },
  { id: 'alment',   name: 'Alment & Sjov',  emoji: '🧠', color: '#FFD23F' },
  { id: 'influencer', name: 'Influencere & TikTok', emoji: '🤳', color: '#FF2E93' },
  { id: 'mix',        name: 'Alt Blandet',          emoji: '🎲', color: '#845EF7' },
];

const QUESTIONS = {
  sommer: {
    nem: [
      { q: "Hvilken dansk ø kaldes 'Solskinsøen' pga. flest solskinstimer i landet?", options: ["Bornholm", "Møn", "Ærø", "Anholt"], correct: "Bornholm", fact: "Bornholm har op mod 1900 solskinstimer om året." },
      { q: "Ifølge den danske ferielov, hvor mange ugers betalt ferie har de fleste lønmodtagere ret til om året?", options: ["5 uger", "4 uger", "6 uger", "3 uger"], correct: "5 uger", fact: "Det svarer til 25 feriedage om året." },
      { q: "I hvilken by ligger Bakken, verdens ældste stadig fungerende forlystelsespark?", options: ["Klampenborg", "Roskilde", "Odense", "Aarhus"], correct: "Klampenborg", fact: "Bakken åbnede allerede i 1583." },
      { q: "I hvilket århundrede fik skolebørns sommerferie i Danmark for alvor sin faste form, bl.a. pga. landbrugets behov for arbejdskraft ved høst?", options: ["1800-tallet", "1900-tallet", "1700-tallet", "2000-tallet"], correct: "1800-tallet", fact: "Skolernes sommerferie skulle oprindeligt sikre arbejdskraft til høsten." },
      { q: "Cirka hvor mange af Danmarks øer er beboede?", options: ["Ca. 70", "Ca. 20", "Ca. 200", "Ca. 400"], correct: "Ca. 70", fact: "Kun omkring en tredjedel af Danmarks øer er beboede." },
      { q: "Hvilken dansk landsdel er kendt for sine lange sandstrande og klitter langs Vesterhavet?", options: ["Vestjylland", "Bornholm", "Sydsjælland", "Nordsjælland"], correct: "Vestjylland", fact: "Klitterne blev plantet til for at stoppe sandflugten i 1800-tallet." },
      { q: "Hvilken type ferie kaldes 'glamping'?", options: ["Luksuscamping", "Vandreferie", "Krydstogt", "Storbyferie"], correct: "Luksuscamping", fact: "Ordet er en sammentrækning af 'glamorous' og 'camping'." },
      { q: "Cirka hvor mange ugers sommerferie har danske folkeskoleelever typisk?", options: ["Ca. 6 uger", "Ca. 2 uger", "Ca. 10 uger", "Ca. 1 uge"], correct: "Ca. 6 uger", fact: "Ferien ligger typisk fra slutningen af juni til starten af august." },
      { q: "Hvilken transportform er kernen i et Interrail-abonnement gennem Europa?", options: ["Tog", "Fly", "Bus", "Cruiseskib"], correct: "Tog", fact: "Med ét kort kan man rejse frit mellem dusinvis af lande." },
      { q: "Hvad kaldes en madkurv, man typisk tager med til stranden eller på skovtur?", options: ["Picnickurv", "Rygsæk", "Kølebox", "Frokosttaske"], correct: "Picnickurv", fact: "Ordet 'picnic' menes at stamme fra fransk." },
    ],
    mellem: [
      { q: "Hvilket år blev Tivoli i København grundlagt?", options: ["1843", "1851", "1900", "1801"], correct: "1843", fact: "Tivoli var inspireret af Vauxhall Gardens i London." },
      { q: "Hvad hedder den spanske tradition i Pamplona, hvor man løber foran tyre gennem gaderne?", options: ["San Fermín", "La Tomatina", "Semana Santa", "Feria de Abril"], correct: "San Fermín", fact: "Festivalen er bedst kendt for tyreløbet 'encierro'." },
      { q: "Hvilket land har verdens længste kystlinje?", options: ["Canada", "Rusland", "Indonesien", "USA"], correct: "Canada", fact: "Canadas kystlinje er over 200.000 km lang, inkl. alle øer og fjorde." },
      { q: "Hvilken by var det klassiske slutmål for de fleste 'Grand Tour'-dannelsesrejser blandt velhavende unge europæere i 1700-tallet?", options: ["Rom", "Paris", "Wien", "Athen"], correct: "Rom", fact: "Rejsen kunne tage flere år og inkluderede ofte også Paris og Venedig." },
      { q: "Hvad kaldes det, når turisme presser lokalbefolkningen ud af boligmarkedet i populære feriebyer?", options: ["Overturisme", "Gentrificering", "Urbanisering", "Migration"], correct: "Overturisme", fact: "Byer som Venedig og Barcelona har indført afgifter for at dæmpe presset." },
      { q: "Hvilken spansk øgruppe i Atlanterhavet er kendt for vulkansk landskab og mildt klima hele året?", options: ["Kanariske Øer", "Balearerne", "Azorerne", "Madeira"], correct: "Kanariske Øer", fact: "Øerne ligger faktisk tættere på Afrika end på Spanien." },
      { q: "Hvad kaldes det, når man booker en rejse uden at kende den endelige destination på forhånd?", options: ["Mystery-/blindrejse", "Standby-rejse", "Backpacking", "Escape-rejse"], correct: "Mystery-/blindrejse", fact: "Konceptet er blevet populært hos flere rejsebureauer de senere år." },
      { q: "Hvilket fransk bjergområde, kendt for Mont Blanc, er populært til både sommer- og vinterferie?", options: ["Alperne", "Pyrenæerne", "Massif Central", "Vogeserne"], correct: "Alperne", fact: "Mont Blanc er Alpernes og Vesteuropas højeste bjerg." },
      { q: "Hvad kaldes en ferie, hvis primære formål er afslapning og sundhed, fx på spa eller kurbad?", options: ["Wellnessferie", "Adventureferie", "Storbyferie", "Kulturferie"], correct: "Wellnessferie", fact: "Wellnessturisme er en af de hurtigst voksende grene af rejsebranchen." },
      { q: "Hvad kaldes en ferie, hvor man arbejder frivilligt mod kost og logi, ofte på økologiske gårde?", options: ["Woofing (WWOOF)", "Backpacking", "Glamping", "Roadtrip"], correct: "Woofing (WWOOF)", fact: "Forkortelsen står for 'World Wide Opportunities on Organic Farms'." },
    ],
    svaer: [
      { q: "Hvornår fik danske lønmodtagere for første gang lovfæstet ret til betalt ferie?", options: ["1938", "1919", "1948", "1960"], correct: "1938", fact: "Loven gav dengang ret til 2 ugers betalt ferie." },
      { q: "Hvad hedder den model, som forskeren Richard Butler i 1980 opstillede til at beskrive en turistdestinations udvikling fra opdagelse til forfald?", options: ["Turismens livscyklus (TALC)", "Bostons matrix", "Maslows behovspyramide", "Porters five forces"], correct: "Turismens livscyklus (TALC)", fact: "Modellen beskriver faser fra opdagelse til stagnation og forfald." },
      { q: "I hvilken by åbnede belgieren Gérard Blitz i 1950 den første Club Med-'landsby' — starten på det moderne all inclusive-koncept?", options: ["Alcúdia, Mallorca", "Cancún", "Ibiza By", "Benidorm"], correct: "Alcúdia, Mallorca", fact: "Konceptet startede som en simpel teltlejr for unge europæere." },
      { q: "Hvilket land har ifølge UNWTO modtaget flest internationale turistankomster hvert år i årtier, inkl. 2019?", options: ["Frankrig", "USA", "Spanien", "Kina"], correct: "Frankrig", fact: "Frankrig har toppet UNWTO's liste over flest internationale turister i årtier." },
      { q: "Hvilken by var det oprindelige mål for Thomas Cooks berømte togudflugt i 1841, som regnes for en af rejsebureau-branchens grundsten?", options: ["Loughborough", "London", "Paris", "Brighton"], correct: "Loughborough", fact: "Turen transporterede omkring 500 rejsende med tog fra Leicester." },
      { q: "Hvilket år blev den første Interrail-billet lanceret, så unge europæere billigt kunne rejse med tog gennem Europa?", options: ["1972", "1960", "1985", "1995"], correct: "1972", fact: "Billetten blev lanceret i anledning af 50-året for den europæiske jernbaneunion." },
      { q: "Hvilket land indførte verdens første nationalpark i 1872 og inspirerede dermed moderne naturturisme globalt?", options: ["USA (Yellowstone)", "Canada", "Sverige", "Kenya"], correct: "USA (Yellowstone)", fact: "Yellowstone dækker et areal større end flere danske regioner tilsammen." },
      { q: "Hvad hedder den franske betegnelse for turisme, hvor formålet er at opleve et lands vinproduktion?", options: ["Oenoturisme", "Gastronomiturisme", "Agroturisme", "Kulturturisme"], correct: "Oenoturisme", fact: "Ordet kommer af det græske 'oinos', som betyder vin." },
      { q: "Hvilken by var i 1851 vært for verdens første internationale verdensudstilling, som satte gang i moderne turisme til storbyer?", options: ["London", "Paris", "New York", "Wien"], correct: "London", fact: "Udstillingen blev afholdt i den berømte glaspalæ-bygning Crystal Palace." },
      { q: "Hvad kaldes det, når man rejser specifikt for at besøge steder forbundet med død og tragedie, som fx Tjernobyl?", options: ["Mørketurisme (dark tourism)", "Adventureturisme", "Ekstremturisme", "Kulturturisme"], correct: "Mørketurisme (dark tourism)", fact: "Begrebet blev for alvor kendt i akademiske kredse i slutningen af 1990'erne." },
    ],
  },
  mad: {
    nem: [
      { q: "Hvilken by regnes for pizzaens fødested?", options: ["Napoli", "Rom", "Milano", "Firenze"], correct: "Napoli", fact: "Pizza Margherita blev opkaldt efter Italiens dronning i 1889." },
      { q: "Hvilket krydderi stammer fra støvfanget på en krokusblomst og er verdens dyreste pr. vægt?", options: ["Safran", "Vanilje", "Muskatnød", "Kardemomme"], correct: "Safran", fact: "Der skal ca. 150 blomster til for at lave 1 gram safran." },
      { q: "Hvad kaldes processen, hvor mælk omdannes til ost ved hjælp af enzymet løbe?", options: ["Koagulering", "Gæring", "Destillation", "Pasteurisering"], correct: "Koagulering", fact: "Løbe indeholder enzymet chymosin, som får mælken til at skille." },
      { q: "Hvilket land er ophavsland for retten paella?", options: ["Spanien", "Portugal", "Italien", "Marokko"], correct: "Spanien", fact: "Paella er opkaldt efter panden, den tilberedes i." },
      { q: "Hvad betyder det italienske udtryk 'al dente' bogstaveligt oversat?", options: ["Til tanden", "Meget blødt", "Perfekt", "Fast"], correct: "Til tanden", fact: "Udtrykket bruges specifikt om pasta, der stadig har en smule bid." },
      { q: "Hvilken frugt er hovedingrediensen i guacamole?", options: ["Avocado", "Mango", "Ananas", "Papaya"], correct: "Avocado", fact: "Avocado er botanisk set et bær, ikke en grøntsag." },
      { q: "Hvilket land er ophavsland for retten tacos?", options: ["Mexico", "Spanien", "Peru", "Argentina"], correct: "Mexico", fact: "Tortillaen, tacoen er lavet af, laves traditionelt af majsmel." },
      { q: "Hvad kaldes en ret, hvor rå fisk marineres i citronsaft, populær i Latinamerika?", options: ["Ceviche", "Tapas", "Antipasto", "Sashimi"], correct: "Ceviche", fact: "Syren i citrussaften 'tilbereder' fisken uden varme." },
      { q: "Hvad hedder den traditionelle britiske eftermiddagste med scones, sandwich og kager?", options: ["Afternoon tea", "High tea", "Brunch", "Cream tea"], correct: "Afternoon tea", fact: "Traditionen menes at stamme fra 1840'erne." },
      { q: "Hvilken varm drik laves ved at brygge ristede og malede kaffebønner i vand?", options: ["Kaffe", "Te", "Kakao", "Chai"], correct: "Kaffe", fact: "Danmark er et af de lande i verden, der drikker mest kaffe pr. indbygger." },
    ],
    mellem: [
      { q: "Hvilken fransk by regnes for landets gastronomiske hovedstad og er hjemsted for kokken Paul Bocuse?", options: ["Lyon", "Paris", "Marseille", "Bordeaux"], correct: "Lyon", fact: "Byen er hjemsted for den legendariske kok Paul Bocuse." },
      { q: "Hvad kaldes en trænet japansk sushikok?", options: ["Itamae", "Wasabi", "Umami", "Nigiri"], correct: "Itamae", fact: "Det kan tage flere år at blive uddannet itamae." },
      { q: "Hvilken 'femte smag' blev identificeret af den japanske kemiker Kikunae Ikeda i 1908?", options: ["Umami", "Salt", "Bitter", "Metallisk"], correct: "Umami", fact: "Ordet betyder groft oversat 'lækker smag' på japansk." },
      { q: "Hvor mange stjerner er det maksimale antal, en restaurant kan opnå i Michelin-guiden?", options: ["3", "5", "4", "1"], correct: "3", fact: "Kun en lille brøkdel af verdens restauranter har opnået 3 stjerner." },
      { q: "Hvilken drue bruges traditionelt til champagne sammen med Chardonnay og Pinot Meunier?", options: ["Pinot Noir", "Merlot", "Cabernet Sauvignon", "Sauvignon Blanc"], correct: "Pinot Noir", fact: "Selvom druen er blå, presses den hurtigt, så vinen forbliver lys." },
      { q: "Hvilket land er verdens største producent af kaffe?", options: ["Brasilien", "Colombia", "Vietnam", "Etiopien"], correct: "Brasilien", fact: "Landet har produceret mest kaffe i verden i over 150 år." },
      { q: "Hvad kaldes den traditionelle japanske teceremoni?", options: ["Chanoyu", "Ikebana", "Origami", "Bonsai"], correct: "Chanoyu", fact: "Ceremonien handler lige så meget om ro og æstetik som om selve teen." },
      { q: "I hvilken by blev den originale Caesar-salat opfundet i 1924 af en italiensk-amerikansk restauratør?", options: ["Tijuana", "Mexico City", "Los Angeles", "San Diego"], correct: "Tijuana", fact: "Salaten er opkaldt efter restauratøren Caesar Cardini, ikke den romerske kejser." },
      { q: "Hvad er hovedingredienserne i den spanske kolde suppe salmorejo, en slægtning til gazpacho?", options: ["Tomat og brød", "Agurk og yoghurt", "Løg og fløde", "Peberfrugt og olie"], correct: "Tomat og brød", fact: "Suppen serveres ofte med kogt æg og skinke som topping." },
      { q: "Hvad kaldes det, når vin bedømmes af en ekspert ud fra duft, farve og smag?", options: ["Vinsmagning/degustation", "Fermentering", "Filtrering", "Destillation"], correct: "Vinsmagning/degustation", fact: "Professionelle vinsmagere kaldes ofte sommelierer." },
    ],
    svaer: [
      { q: "Hvilken fransk by regnes for champagnens historiske hovedby og er hjemsted for producenter som Moët & Chandon?", options: ["Épernay", "Reims", "Dijon", "Nice"], correct: "Épernay", fact: "Byen kaldes ofte champagnens hovedstad." },
      { q: "Hvad hedder den kemiske reaktion mellem aminosyrer og sukkerarter, der giver stegt mad dens brune farve og smag, opkaldt efter en fransk kemiker?", options: ["Maillard-reaktionen", "Karamellisering", "Fotosyntese", "Oxidering"], correct: "Maillard-reaktionen", fact: "Reaktionen kræver typisk temperaturer over ca. 140°C." },
      { q: "I hvilket årti udviklede den franske kok Georges Pralus den moderne sous-vide-teknik?", options: ["1970'erne", "1950'erne", "1990'erne", "2000'erne"], correct: "1970'erne", fact: "Metoden bruges i dag også af hjemmekokke med vandbade." },
      { q: "Hvilken by huser Botín, som ifølge Guinness Rekordbog er verdens ældste stadig fungerende restaurant, grundlagt i 1725?", options: ["Madrid", "Rom", "Paris", "Lissabon"], correct: "Madrid", fact: "Restauranten nævnes bl.a. i Ernest Hemingways romaner." },
      { q: "Hvad hedder det franske klassifikationssystem fra 1855, der rangerer Bordeaux-vine efter kvalitet?", options: ["Bordeaux-klassifikationen af 1855", "Appellation d'Origine Contrôlée", "Grand Cru Classé", "Denominazione di Origine"], correct: "Bordeaux-klassifikationen af 1855", fact: "Kun fem vine opnåede oprindeligt den højeste rang, Premier Cru." },
      { q: "I hvilket år udkom den første Michelin-guide, oprindeligt lavet som en gratis vejledning til bilister?", options: ["1900", "1926", "1950", "1875"], correct: "1900", fact: "Guiden blev udgivet af dækproducenten Michelin." },
      { q: "Hvilken by huser det legendariske restaurantkoncept 'El Bulli', kendt for molekylær gastronomi under kokken Ferran Adrià?", options: ["Roses", "Barcelona", "Madrid", "Girona"], correct: "Roses", fact: "Restauranten lå på Costa Brava og lukkede i 2011." },
      { q: "Hvad kaldes den kulinariske retning, hvor mad tilberedes med kemiske teknikker for at skabe uventede teksturer, som fx skum og geléer?", options: ["Molekylær gastronomi", "Sous-vide", "Fermentering", "Konfitering"], correct: "Molekylær gastronomi", fact: "Retningen blev for alvor populær i starten af 2000'erne." },
      { q: "Hvilken dansk restaurant er flere gange blevet kåret som verdens bedste af listen 'The World's 50 Best Restaurants'?", options: ["Noma", "Geranium", "Kong Hans Kælder", "AOC"], correct: "Noma", fact: "Restauranten har toppet listen flere gange siden 2010." },
      { q: "Hvad hedder den lovbeskyttede franske ost, der kun må produceres i en bestemt region omkring en by af samme navn?", options: ["Roquefort", "Camembert", "Brie", "Comté"], correct: "Roquefort", fact: "Osten modnes traditionelt i naturlige kalkstensgrotter." },
    ],
  },
  film: {
    nem: [
      { q: "Hvem instruerede filmene 'Jaws', 'E.T.' og 'Jurassic Park'?", options: ["Steven Spielberg", "James Cameron", "George Lucas", "Christopher Nolan"], correct: "Steven Spielberg", fact: "Han er en af filmhistoriens mest indtjenende instruktører." },
      { q: "Hvilken skuespiller spillede Jack Dawson i 'Titanic' fra 1997?", options: ["Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Tom Cruise"], correct: "Leonardo DiCaprio", fact: "Filmen vandt hele 11 Oscars." },
      { q: "Hvad hedder troldmandsskolen i Harry Potter-universet?", options: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"], correct: "Hogwarts", fact: "Navnet betyder groft oversat 'vortesvin'." },
      { q: "Hvilket studie producerede 'Toy Story' i 1995, verdens første fuldt computeranimerede spillefilm?", options: ["Pixar", "DreamWorks", "Illumination", "Blue Sky Studios"], correct: "Pixar", fact: "Filmen krævede enorme mængder computertid at rendere." },
      { q: "Hvilken dansk instruktør vandt Oscar for bedste fremmedsprogede film med 'Babettes gæstebud' i 1988?", options: ["Gabriel Axel", "Lars von Trier", "Bille August", "Susanne Bier"], correct: "Gabriel Axel", fact: "Det var Danmarks første Oscar i denne kategori." },
      { q: "Hvilken skuespiller spiller Iron Man/Tony Stark i Marvel-filmene?", options: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"], correct: "Robert Downey Jr.", fact: "Rollen genoplivede hans karriere efter en svær periode i 1990'erne." },
      { q: "Hvad hedder Disney-filmen om isprinsessen Elsa, der kan skabe sne og is?", options: ["Frost", "Modig", "Coco", "Vaiana"], correct: "Frost", fact: "Filmen er løst inspireret af H.C. Andersens 'Snedronningen'." },
      { q: "Hvilket land producerer flest spillefilm om året, ofte forbundet med filmindustrien 'Bollywood'?", options: ["Indien", "USA", "Kina", "Frankrig"], correct: "Indien", fact: "Bollywood er navnet på den hindisprogede del af industrien i Mumbai." },
      { q: "Hvem spiller rollen som kaptajn Jack Sparrow i 'Pirates of the Caribbean'?", options: ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Keira Knightley"], correct: "Johnny Depp", fact: "Rollen var delvist inspireret af musikeren Keith Richards." },
      { q: "Hvilken TV-serie handler om familien Stark og kampen om Jerntronen?", options: ["Game of Thrones", "Vikings", "The Crown", "Outlander"], correct: "Game of Thrones", fact: "Serien er baseret på George R.R. Martins bogserie." },
    ],
    mellem: [
      { q: "Hvilken skuespiller har vundet Oscar for bedste mandlige hovedrolle flest gange (3 gange)?", options: ["Daniel Day-Lewis", "Jack Nicholson", "Tom Hanks", "Marlon Brando"], correct: "Daniel Day-Lewis", fact: "Han er kendt for ekstrem metode-skuespil." },
      { q: "Hvem grundlagde Dogme 95-bevægelsen sammen med Thomas Vinterberg?", options: ["Lars von Trier", "Nicolas Winding Refn", "Susanne Bier", "Bille August"], correct: "Lars von Trier", fact: "Dogme 95 krævede bl.a. håndholdt kamera og naturligt lys." },
      { q: "Hvilken film var i 1934 den første til at vinde de såkaldte 'Big Five' Oscars?", options: ["Det skete en nat", "Borte med blæsten", "Casablanca", "Rebecca"], correct: "Det skete en nat", fact: "Bedriften er kun gentaget to gange siden i Oscar-historien." },
      { q: "Hvilken bygning husede den allerførste Oscar-uddeling i 1929?", options: ["Hotel Roosevelt", "Dolby Theatre", "Kodak Theatre", "Shrine Auditorium"], correct: "Hotel Roosevelt", fact: "Kun omkring 270 gæster deltog i den 15 minutter lange ceremoni." },
      { q: "Hvem komponerede den ikoniske filmmusik til 'Star Wars', 'Jaws' og 'Jurassic Park'?", options: ["John Williams", "Hans Zimmer", "Ennio Morricone", "Danny Elfman"], correct: "John Williams", fact: "Han har komponeret musik til over 100 film." },
      { q: "Hvilken film fra 1994 med Tom Hanks handler om en mand, der ufrivilligt påvirker store historiske begivenheder?", options: ["Forrest Gump", "Cast Away", "The Green Mile", "Philadelphia"], correct: "Forrest Gump", fact: "Filmen vandt Oscar for bedste film samme år." },
      { q: "Hvem instruerede filmtrilogien 'Ringenes Herre'?", options: ["Peter Jackson", "James Cameron", "Christopher Nolan", "Ridley Scott"], correct: "Peter Jackson", fact: "Alle tre film blev optaget samtidig i New Zealand." },
      { q: "Hvilken skuespillerinde spillede Katniss Everdeen i filmatiseringerne af 'Hunger Games'?", options: ["Jennifer Lawrence", "Emma Watson", "Kristen Stewart", "Shailene Woodley"], correct: "Jennifer Lawrence", fact: "Hun blev en af de yngste til nogensinde at vinde en skuespiller-Oscar." },
      { q: "Hvilken dansk instruktør står bag filmene 'Festen' og 'Jagten'?", options: ["Thomas Vinterberg", "Lars von Trier", "Nicolas Winding Refn", "Susanne Bier"], correct: "Thomas Vinterberg", fact: "'Festen' var den første officielle Dogme 95-film." },
      { q: "Hvilket studie vandt den allerførste Oscar for bedste animationsfilm i 2002 med 'Shrek'?", options: ["DreamWorks", "Pixar", "Disney", "Illumination"], correct: "DreamWorks", fact: "Prisen blev indstiftet i 2001 og uddelt for første gang året efter." },
    ],
    svaer: [
      { q: "Hvilken film vandt det allerførste Oscar for bedste film i 1929?", options: ["Wings", "Sunrise", "The Jazz Singer", "Metropolis"], correct: "Wings", fact: "Filmen var en stumfilm om jagerpiloter i 1. verdenskrig." },
      { q: "Hvad hedder den franske filmbevægelse fra slutningen af 1950'erne, kendt for instruktører som Jean-Luc Godard og François Truffaut?", options: ["Nouvelle Vague", "Neorealisme", "Expressionisme", "Dogme 95"], correct: "Nouvelle Vague", fact: "Bevægelsen brød med traditionel filmteknik og -fortælling." },
      { q: "Hvilken skuespillerinde har modtaget flest Oscar-nomineringer for bedste kvindelige hovedrolle gennem tiden?", options: ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Cate Blanchett"], correct: "Meryl Streep", fact: "Hun har vundet prisen tre gange ud af sine mange nomineringer." },
      { q: "I hvilket år blev Cannes Film Festival første gang afholdt, efter at være udsat pga. krigen?", options: ["1946", "1932", "1955", "1939"], correct: "1946", fact: "Festivalen skulle egentlig være startet i 1939." },
      { q: "Hvilken italiensk instruktør står bag neorealisme-klassikeren 'Cykeltyven' (Ladri di biciclette)?", options: ["Vittorio De Sica", "Federico Fellini", "Michelangelo Antonioni", "Roberto Rossellini"], correct: "Vittorio De Sica", fact: "Filmen bruges ofte som skoleeksempel på italiensk neorealisme." },
      { q: "Hvilken instruktør har vundet flest Oscar for bedste instruktør gennem tiden (4 gange)?", options: ["John Ford", "Steven Spielberg", "William Wyler", "Frank Capra"], correct: "John Ford", fact: "Han vandt bl.a. for westernfilm og krigsdramaer." },
      { q: "Hvilken film var i 1997 den første til at tjene over 1 milliard dollars ved biografkasserne på verdensplan?", options: ["Titanic", "Star Wars", "Jaws", "E.T."], correct: "Titanic", fact: "Filmen beholdt rekorden som mest indtjenende film i over ti år." },
      { q: "I hvilket årti opstod den tyske ekspressionistiske filmstil, kendt for skæve kulisser og dramatiske skygger?", options: ["1920'erne", "1930'erne", "1910'erne", "1940'erne"], correct: "1920'erne", fact: "Stilen har inspireret senere gyser- og film noir-genrer markant." },
      { q: "Hvilken amerikansk skuespillerinde har vundet flest Oscar for bedste kvindelige hovedrolle gennem tiden (4 gange)?", options: ["Katharine Hepburn", "Meryl Streep", "Bette Davis", "Ingrid Bergman"], correct: "Katharine Hepburn", fact: "Hun holder stadig rekorden mange årtier senere." },
      { q: "Hvilket år blev den originale 'Star Wars'-film (senere Episode IV) udgivet?", options: ["1977", "1980", "1975", "1983"], correct: "1977", fact: "Filmen ændrede filmindustrien og skabte hele merchandise-branchen." },
    ],
  },
  musik: {
    nem: [
      { q: "Hvilken østrigsk komponist skrev 'Eine kleine Nachtmusik' og døde kun 35 år gammel?", options: ["Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Franz Schubert", "Joseph Haydn"], correct: "Wolfgang Amadeus Mozart", fact: "Han skrev over 600 værker i sit korte liv." },
      { q: "Hvilket svensk band skrev og sang 'Dancing Queen' og vandt Eurovision i 1974 med 'Waterloo'?", options: ["ABBA", "Roxette", "Ace of Base", "A-ha"], correct: "ABBA", fact: "Bandnavnet er dannet af medlemmernes forbogstaver." },
      { q: "Hvem er kendt som 'King of Pop'?", options: ["Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"], correct: "Michael Jackson", fact: "Han har solgt over 750 millioner plader på verdensplan." },
      { q: "Hvilken dansk sangerinde vandt Eurovision Song Contest for Danmark i 2013 med 'Only Teardrops'?", options: ["Emmelie de Forest", "Basim", "Rasmus Seebach", "MØ"], correct: "Emmelie de Forest", fact: "Sangen var Danmarks tredje Eurovision-sejr." },
      { q: "Hvor mange strenge har en klassisk (spansk) guitar normalt?", options: ["6", "4", "8", "12"], correct: "6", fact: "Nogle basguitarer har til sammenligning kun 4 strenge." },
      { q: "Hvilken britisk sanger er kendt for hittet 'Shape of You'?", options: ["Ed Sheeran", "Sam Smith", "Harry Styles", "Robbie Williams"], correct: "Ed Sheeran", fact: "Sangen lå i lang tid øverst på hitlisterne verden over." },
      { q: "Hvor mange tangenter har et almindeligt klaver normalt?", options: ["88", "76", "100", "64"], correct: "88", fact: "Det svarer til 52 hvide og 36 sorte tangenter." },
      { q: "Hvilken amerikansk sangerinde er kendt som 'Queen of Pop'?", options: ["Madonna", "Beyoncé", "Britney Spears", "Lady Gaga"], correct: "Madonna", fact: "Hun har haft en karriere, der strækker sig over fire årtier." },
      { q: "Hvilken dansk sangerinde er kendt for hittet 'Pilot' med DJ'en Diplo?", options: ["MØ", "Aura Dione", "Medina", "Oh Land"], correct: "MØ", fact: "MØ har også sunget med på flere internationale hits." },
      { q: "Hvilket britisk band bestod af John, Paul, George og Ringo?", options: ["The Beatles", "The Rolling Stones", "Queen", "Pink Floyd"], correct: "The Beatles", fact: "Bandet regnes af mange som det mest indflydelsesrige i populærmusikkens historie." },
    ],
    mellem: [
      { q: "Hvem komponerede balletten 'Svanesøen'?", options: ["Pjotr Tjajkovskij", "Sergej Prokofjev", "Igor Stravinskij", "Johannes Brahms"], correct: "Pjotr Tjajkovskij", fact: "Balletten blev første gang opført i Moskva i 1877." },
      { q: "Hvilket dansk symfoniorkester, grundlagt i 1448, regnes som et af verdens ældste?", options: ["Det Kongelige Kapel", "DR SymfoniOrkestret", "Aarhus Symfoniorkester", "Sjællands Symfoniorkester"], correct: "Det Kongelige Kapel", fact: "Orkestret spiller stadig faste forestillinger på Det Kongelige Teater." },
      { q: "Hvem opfandt saxofonen i 1840'erne?", options: ["Adolphe Sax", "Theobald Boehm", "Antonio Stradivari", "Johann Strauss"], correct: "Adolphe Sax", fact: "Han var oprindeligt fra Belgien, men arbejdede det meste af livet i Paris." },
      { q: "Hvilket album regnes ifølge de fleste opgørelser for verdens bedst sælgende nogensinde?", options: ["Thriller (Michael Jackson)", "Back in Black (AC/DC)", "The Dark Side of the Moon (Pink Floyd)", "Rumours (Fleetwood Mac)"], correct: "Thriller (Michael Jackson)", fact: "Albummet er solgt i over 70 millioner eksemplarer." },
      { q: "Hvilken komponist nåede ikke at færdiggøre operaen 'Turandot' før sin død i 1924?", options: ["Giacomo Puccini", "Giuseppe Verdi", "Gioachino Rossini", "Gaetano Donizetti"], correct: "Giacomo Puccini", fact: "Han nåede aldrig at høre sit værk blive opført." },
      { q: "Hvilken komponist skrev violinkoncertsamlingen 'De fire årstider'?", options: ["Antonio Vivaldi", "Johann Sebastian Bach", "Georg Friedrich Händel", "Domenico Scarlatti"], correct: "Antonio Vivaldi", fact: "Værket er et af de mest genkendelige stykker i hele den klassiske musik." },
      { q: "Hvilket britisk band udgav det ikoniske album 'The Dark Side of the Moon' i 1973?", options: ["Pink Floyd", "Led Zeppelin", "The Who", "Queen"], correct: "Pink Floyd", fact: "Albumcoveret med prismet er et af rockmusikkens mest genkendelige." },
      { q: "Hvem skrev teksten til den danske nationalsang 'Der er et yndigt land'?", options: ["Adam Oehlenschläger", "H.C. Andersen", "N.F.S. Grundtvig", "Johannes V. Jensen"], correct: "Adam Oehlenschläger", fact: "Melodien er komponeret af Hans Ernst Krøyer." },
      { q: "Hvilken musikgenre har rødder i New Orleans og er kendt for improvisation og synkoperede rytmer?", options: ["Jazz", "Blues", "Reggae", "Folk"], correct: "Jazz", fact: "Genren opstod i slutningen af 1800-tallet og starten af 1900-tallet." },
      { q: "Hvilke fire medlemmer bestod den svenske popgruppe ABBA af?", options: ["Björn, Benny, Agnetha og Anni-Frid", "John, Paul, George og Ringo", "Mick, Keith, Charlie og Ronnie", "Freddie, Brian, Roger og John"], correct: "Björn, Benny, Agnetha og Anni-Frid", fact: "Gruppen dannede sig officielt i Stockholm i 1972." },
    ],
    svaer: [
      { q: "Hvem komponerede sin 'Requiem' på dødslejet i 1791, hvorefter en elev fuldførte værket?", options: ["Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Franz Schubert", "Antonio Salieri"], correct: "Wolfgang Amadeus Mozart", fact: "Han døde, mens han stadig arbejdede på værket, kun 35 år gammel." },
      { q: "Hvilken komponist var stort set stokdøv, da han skrev sin 9. symfoni?", options: ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johannes Brahms", "Franz Liszt"], correct: "Ludwig van Beethoven", fact: "Han skal angiveligt have brugt et savet klaver for bedre at mærke vibrationerne." },
      { q: "Hvad hedder det system, hvor alle 12 toner i den kromatiske skala bruges ligeværdigt, udviklet af Arnold Schönberg i starten af 1920'erne?", options: ["Tolvtonemusik (dodekafoni)", "Serialisme", "Atonalitet", "Minimalisme"], correct: "Tolvtonemusik (dodekafoni)", fact: "Teknikken bryder bevidst med traditionel toneart og harmonik." },
      { q: "I hvilken by havde Wolfgang Amadeus Mozart sin første ansættelse som hofkomponist?", options: ["Salzburg", "Wien", "Prag", "München"], correct: "Salzburg", fact: "Han blev senere uvenner med sin arbejdsgiver, ærkebiskoppen." },
      { q: "Hvilken russiske komponists ballet 'Le Sacre du Printemps' forårsagede optøjer ved premieren i Paris i 1913?", options: ["Igor Stravinskij", "Pjotr Tjajkovskij", "Sergej Prokofjev", "Dmitrij Sjostakovitj"], correct: "Igor Stravinskij", fact: "Publikum kom angiveligt i håndgemæng under premieren." },
      { q: "Hvilken fransk komponist skrev operaen 'Carmen', der havde premiere i Paris i 1875?", options: ["Georges Bizet", "Giuseppe Verdi", "Giacomo Puccini", "Richard Wagner"], correct: "Georges Bizet", fact: "Bizet døde blot tre måneder efter premieren og oplevede aldrig operaens succes." },
      { q: "Hvilken tysk komponist er kendt for sine 'Brandenburgske Koncerter'?", options: ["Johann Sebastian Bach", "Georg Friedrich Händel", "Ludwig van Beethoven", "Johannes Brahms"], correct: "Johann Sebastian Bach", fact: "Værkerne blev oprindeligt tilegnet en tysk markgreve." },
      { q: "Hvad betyder den italienske musikbetegnelse 'fortissimo'?", options: ["Meget kraftigt", "Meget svagt", "Hurtigt", "Langsomt"], correct: "Meget kraftigt", fact: "Det modsatte, meget svagt, hedder 'pianissimo'." },
      { q: "Hvad kaldes myten om, at komponister som Beethoven, Bruckner og Mahler alle døde kort efter deres niende symfoni?", options: ["Den niendes forbandelse", "Komponistens forbandelse", "Symfoniens forbandelse", "Den sidste toneart"], correct: "Den niendes forbandelse", fact: "Myten opstod, fordi flere store komponister aldrig nåede en tiende symfoni." },
      { q: "Hvilken russisk komponist skrev '1812-ouverturen' til minde om Ruslands sejr over Napoleon?", options: ["Pjotr Tjajkovskij", "Igor Stravinskij", "Sergej Rachmaninov", "Modest Mussorgskij"], correct: "Pjotr Tjajkovskij", fact: "Værket bruges den dag i dag ofte til fyrværkeri-koncerter." },
    ],
  },
  geografi: {
    nem: [
      { q: "Hvad hedder verdens højeste bjerg målt fra havoverfladen?", options: ["Mount Everest", "K2", "Kangchenjunga", "Denali"], correct: "Mount Everest", fact: "Bjerget er 8.849 meter højt." },
      { q: "Hvilket land har flest indbyggere i verden i dag?", options: ["Indien", "Kina", "USA", "Indonesien"], correct: "Indien", fact: "Indien overhalede Kina som verdens mest folkerige land i 2023." },
      { q: "Hvad hedder verdens største varme ørken?", options: ["Sahara", "Gobi", "Kalahari", "Atacama"], correct: "Sahara", fact: "Sahara er næsten lige så stor som hele USA." },
      { q: "Hvilken by kaldes 'Den Evige Stad'?", options: ["Rom", "Athen", "Jerusalem", "Istanbul"], correct: "Rom", fact: "Tilnavnet hentyder til byens lange, uafbrudte historie." },
      { q: "Hvad hedder verdens mindste selvstændige land målt i areal?", options: ["Vatikanstaten", "Monaco", "San Marino", "Liechtenstein"], correct: "Vatikanstaten", fact: "Landet er kun ca. 0,44 kvadratkilometer stort." },
      { q: "Hvilket land har form som en støvle på landkortet?", options: ["Italien", "Grækenland", "Spanien", "Portugal"], correct: "Italien", fact: "'Støvlespidsen' peger mod øen Sicilien." },
      { q: "Hvilket kontinent er det største målt i areal?", options: ["Asien", "Afrika", "Nordamerika", "Europa"], correct: "Asien", fact: "Asien dækker omkring 30% af Jordens samlede landareal." },
      { q: "Hvilken flod regnes traditionelt for verdens længste og løber gennem Egypten?", options: ["Nilen", "Amazonfloden", "Yangtzefloden", "Mississippi"], correct: "Nilen", fact: "Nyere målinger peger dog på, at Amazonfloden muligvis er endnu længere." },
      { q: "Hvad hedder verdens største ocean?", options: ["Stillehavet", "Atlanterhavet", "Det Indiske Ocean", "Det Arktiske Ocean"], correct: "Stillehavet", fact: "Det dækker over en tredjedel af Jordens overflade." },
      { q: "Hvad er Frankrigs hovedstad?", options: ["Paris", "Lyon", "Marseille", "Nice"], correct: "Paris", fact: "Byen har omkring 2 millioner indbyggere i selve bykernen." },
    ],
    mellem: [
      { q: "Hvilke to lande deler verdens længste landegrænse?", options: ["USA og Canada", "Rusland og Kina", "Kasakhstan og Rusland", "Chile og Argentina"], correct: "USA og Canada", fact: "Grænsen er over 8.800 km lang." },
      { q: "Hvilken by er verdens nordligste hovedstad i et selvstændigt land?", options: ["Reykjavik", "Oslo", "Helsinki", "Ottawa"], correct: "Reykjavik", fact: "Byen ligger så langt nordpå, at somrene har lyse nætter." },
      { q: "Hvilket land består af over 17.000 øer og er verdens største østat?", options: ["Indonesien", "Filippinerne", "Japan", "New Zealand"], correct: "Indonesien", fact: "Kun omkring 6.000 af landets øer er beboede." },
      { q: "Hvad hedder verdens dybeste sø, som indeholder cirka 20% af verdens ferske overfladevand?", options: ["Bajkalsøen", "Det Kaspiske Hav", "Tanganyikasøen", "Victoriasøen"], correct: "Bajkalsøen", fact: "Søen er over 1.600 meter dyb og millioner af år gammel." },
      { q: "Hvilket land har flest tidszoner, når man tæller alle oversøiske territorier med?", options: ["Frankrig", "Rusland", "USA", "Storbritannien"], correct: "Frankrig", fact: "De ekstra tidszoner skyldes bl.a. Fransk Polynesien og Guadeloupe." },
      { q: "Hvilket land strækker sig over ca. fem geografiske tidszoner, men bruger officielt kun én tid i hele landet?", options: ["Kina", "Rusland", "USA", "Canada"], correct: "Kina", fact: "Hele landet følger Beijing-tid, uanset hvor langt mod vest man befinder sig." },
      { q: "Hvilken ørken regnes for verdens største, når man også tæller kolde ørkener med?", options: ["Antarktis", "Sahara", "Gobi", "Arktis"], correct: "Antarktis", fact: "En ørken defineres ud fra nedbørsmængde, ikke temperatur." },
      { q: "Hvilket land ligger på to kontinenter, med en del af hovedstaden på hver side af et stræde?", options: ["Tyrkiet", "Rusland", "Kasakhstan", "Georgien"], correct: "Tyrkiet", fact: "Istanbul er delt af Bosporusstrædet mellem Europa og Asien." },
      { q: "Hvad hedder verdens højeste vandfald, beliggende i Venezuela?", options: ["Angel Falls", "Victoria Falls", "Niagara Falls", "Iguazu Falls"], correct: "Angel Falls", fact: "Vandet falder mere end 900 meter fra et bjergplateau." },
      { q: "Hvilket afrikansk land har flest officielle sprog, med hele 11 anerkendte sprog?", options: ["Sydafrika", "Nigeria", "Kenya", "Etiopien"], correct: "Sydafrika", fact: "Blandt sprogene er bl.a. zulu, xhosa, afrikaans og engelsk." },
    ],
    svaer: [
      { q: "Hvad hedder verdens mest isolerede beboede øgruppe, hvor nærmeste nabo er over 2000 km væk?", options: ["Tristan da Cunha", "Påskeøen", "Socotra", "Saint Helena"], correct: "Tristan da Cunha", fact: "Nærmeste beboede nabo er Sankt Helena, ca. 2.400 km væk." },
      { q: "Hvilket land har historisk tre officielle hovedstæder — én for hver statsmagt?", options: ["Sydafrika", "Bolivia", "Sri Lanka", "Malaysia"], correct: "Sydafrika", fact: "Johannesburg er landets største by, men ikke en af hovedstæderne." },
      { q: "Hvilket stræde adskiller Rusland og USA og er kun ca. 4 km bredt mellem Diomedeøerne på det smalleste sted?", options: ["Beringstrædet", "Nordvestpassagen", "Malaccastrædet", "Dover-strædet"], correct: "Beringstrædet", fact: "Om vinteren kan strædet delvist fryse til." },
      { q: "Hvilket lille land grænser op til både Frankrig og Spanien uden selv at være medlem af EU?", options: ["Andorra", "Monaco", "San Marino", "Liechtenstein"], correct: "Andorra", fact: "Landet styres traditionelt af to statsoverhoveder — Frankrigs præsident og en spansk biskop." },
      { q: "Hvad hedder den zoogeografiske linje, opkaldt efter en britisk naturforsker, der adskiller Asiens og Australiens dyreliv?", options: ["Wallace-linjen", "Mercator-linjen", "Meridianen", "Richter-linjen"], correct: "Wallace-linjen", fact: "Linjen forklarer bl.a., hvorfor pungdyr findes øst for linjen, men ikke vest for." },
      { q: "Hvilket land er det eneste, der grænser op til både Sortehavet og Det Kaspiske Hav?", options: ["Rusland", "Georgien", "Tyrkiet", "Iran"], correct: "Rusland", fact: "Ingen andre lande har kyst til begge have på samme tid." },
      { q: "Hvad hedder den kunstige vandvej, der forbinder Middelhavet med Det Røde Hav, åbnet i 1869?", options: ["Suezkanalen", "Panamakanalen", "Kielkanalen", "Corinthkanalen"], correct: "Suezkanalen", fact: "Kanalen forkorter sørejsen mellem Europa og Asien markant." },
      { q: "Hvilket land har verdens laveste befolkningstæthed blandt alle selvstændige lande (Antarktis undtaget)?", options: ["Mongoliet", "Island", "Australien", "Canada"], correct: "Mongoliet", fact: "Store dele af landet består af den golde Gobi-ørken." },
      { q: "Hvad hedder den grænselinje, der historisk adskilte det kommunistiske Østeuropa fra det demokratiske Vesteuropa under Den Kolde Krig?", options: ["Jerntæppet", "Berlinmuren", "Maginotlinjen", "Oder-Neisse-linjen"], correct: "Jerntæppet", fact: "Udtrykket blev populariseret af Winston Churchill i en tale i 1946." },
      { q: "Hvilken by var i mange år delt af en mur mellem øst og vest indtil 1989?", options: ["Berlin", "Wien", "Prag", "Budapest"], correct: "Berlin", fact: "Muren faldt den 9. november 1989." },
    ],
  },
  dyr: {
    nem: [
      { q: "Hvilket dyr er verdens største nulevende landdyr?", options: ["Elefant", "Flodhest", "Næsehorn", "Giraf"], correct: "Elefant", fact: "En voksen elefant kan veje op mod 6 tons." },
      { q: "Hvor mange ben har en edderkop?", options: ["8", "6", "10", "4"], correct: "8", fact: "Edderkopper er ikke insekter, men spindlere." },
      { q: "Hvilket havdyr er verdens største nulevende dyr overhovedet?", options: ["Blåhval", "Kaskelothval", "Hvid haj", "Spækhugger"], correct: "Blåhval", fact: "Blåhvalens hjerte alene kan veje omkring 180 kg." },
      { q: "Hvad hedder verdens højeste dyr?", options: ["Giraf", "Elefant", "Struds", "Kamel"], correct: "Giraf", fact: "En giraf kan blive op til 5-6 meter høj." },
      { q: "Hvilket dyr kan ændre farve for primært at kommunikere og kamuflere sig?", options: ["Kamæleon", "Frø", "Slange", "Firben"], correct: "Kamæleon", fact: "Kamæleoner skifter primært farve for at kommunikere, ikke kun for camouflage." },
      { q: "Hvilket havdyr er kendt for sin høje intelligens og evne til at bruge redskaber?", options: ["Blæksprutte", "Sild", "Krabbe", "Søstjerne"], correct: "Blæksprutte", fact: "Blæksprutter kan bl.a. finde vej ud af lukkede glas." },
      { q: "Hvor mange hjerter har et menneske?", options: ["1", "2", "3", "4"], correct: "1", fact: "Til sammenligning har en blæksprutte hele tre hjerter." },
      { q: "Hvilket dyr kaldes ofte 'ørkenens skib' pga. dets evne til at krydse ørkener?", options: ["Kamel", "Hest", "Ged", "Æsel"], correct: "Kamel", fact: "Kamelens pukkel gemmer på fedt, ikke vand." },
      { q: "Hvilket dyr lægger æg, selvom det er et pattedyr?", options: ["Næbdyr", "Kænguru", "Koala", "Pindsvin"], correct: "Næbdyr", fact: "Næbdyret lever kun i Australien." },
      { q: "Hvor mange arme har en søstjerne typisk?", options: ["5", "4", "6", "8"], correct: "5", fact: "Nogle arter kan dog have langt flere arme end det." },
    ],
    mellem: [
      { q: "Hvor mange hjerter har en blæksprutte?", options: ["3", "1", "2", "4"], correct: "3", fact: "To af hjerterne pumper blod til gællerne, det tredje til resten af kroppen." },
      { q: "Hvilket dyr sover med kun det halve af hjernen ad gangen?", options: ["Delfin", "Kat", "Hund", "Sæl"], correct: "Delfin", fact: "Det kaldes unihemisfærisk søvn." },
      { q: "Hvad kaldes fænomenet, hvor dyr som bjørne sænker stofskiftet markant og sover det meste af vinteren?", options: ["Hi/dvale", "Æstivation", "Diapause", "Torpor"], correct: "Hi/dvale", fact: "Under dvale sænkes puls og stofskifte markant." },
      { q: "Hvilken flyveudygtig fugl er verdens hurtigste løber blandt fugle?", options: ["Struds", "Emu", "Pingvin", "Kiwi"], correct: "Struds", fact: "En struds kan løbe op til 70 km/t." },
      { q: "Hvad er Danmarks nationalfugl?", options: ["Knopsvane", "Stork", "Ørn", "Ugle"], correct: "Knopsvane", fact: "Knopsvanen er en af Danmarks tungeste flyvende fugle." },
      { q: "Hvilket dyr er verdens hurtigste landdyr over korte afstande?", options: ["Gepard", "Løve", "Hest", "Struds"], correct: "Gepard", fact: "Geparden kan accelerere fra 0 til 100 km/t på under 3 sekunder." },
      { q: "Hvad kaldes en gruppe løver?", options: ["Flok", "Hjord", "Stime", "Sværm"], correct: "Flok", fact: "En løveflok kan bestå af op til 30 dyr." },
      { q: "Hvilket dyr har den længste kendte levetid blandt pattedyr, muligvis over 200 år?", options: ["Grønlandshval", "Elefant", "Blåhval", "Skildpadde"], correct: "Grønlandshval", fact: "Alderen kan bl.a. bestemmes ud fra kemiske stoffer i hvalens øjenlinse." },
      { q: "Hvilken fugl er kendt for at kunne efterligne menneskestemmer og andre lyde?", options: ["Papegøje", "Ravn", "Due", "Måge"], correct: "Papegøje", fact: "Nogle papegøjearter kan lære over 100 ord." },
      { q: "Hvor mange øjne har de fleste edderkopper typisk?", options: ["8", "2", "4", "6"], correct: "8", fact: "Trods de mange øjne har mange edderkopper faktisk dårligt syn." },
    ],
    svaer: [
      { q: "Cirka hvor mange 'hjerter' (aortabuer) har en regnorm?", options: ["10 (5 par)", "1", "3", "4 (2 par)"], correct: "10 (5 par)", fact: "De fungerer som pumper for regnormens blodkredsløb." },
      { q: "Hvilket dyr har det stærkeste målte bid blandt nulevende landdyr?", options: ["Saltvandskrokodille", "Løve", "Tiger", "Flodhest"], correct: "Saltvandskrokodille", fact: "Bidkraften er målt til over 3.700 psi." },
      { q: "Hvilken hvalart har det største kendte dyrehjerte, der kan veje op mod 180 kg?", options: ["Blåhval", "Kaskelothval", "Pukkelhval", "Finhval"], correct: "Blåhval", fact: "Hjertet er cirka på størrelse med en lille bil." },
      { q: "Hvad kaldes fænomenet, hvor visse dyrearter kan reproducere sig uden befrugtning fra hanner?", options: ["Partenogenese", "Metamorfose", "Symbiose", "Mitose"], correct: "Partenogenese", fact: "Det ses bl.a. hos visse haj-, firben- og insektarter." },
      { q: "Hvilket dyr har det største øje blandt alle kendte nulevende dyr, op til ca. 27 cm i diameter?", options: ["Kæmpeblæksprutte", "Blåhval", "Struds", "Hvid haj"], correct: "Kæmpeblæksprutte", fact: "Det enorme øje hjælper den med at spotte kaskelothvaler i mørket." },
      { q: "Hvilket dyr er det eneste pattedyr, der kan flyve aktivt (ikke bare glide)?", options: ["Flagermus", "Flyveegern", "Flyvefisk", "Sukkerglider"], correct: "Flagermus", fact: "Flagermus navigerer typisk vha. ekkolokalisering i mørke." },
      { q: "Hvad kaldes fænomenet, hvor et dyr kan gendanne mistede kropsdele, som fx en salamander kan med sin hale?", options: ["Regeneration", "Metamorfose", "Mutation", "Partenogenese"], correct: "Regeneration", fact: "Nogle salamanderarter kan endda gendanne dele af hjertet." },
      { q: "Hvilket insekt kan løfte op til 50 gange sin egen kropsvægt?", options: ["Myre", "Bille", "Bi", "Sommerfugl"], correct: "Myre", fact: "I forhold til kropsstørrelse er myrer blandt de stærkeste dyr på Jorden." },
      { q: "Hvilket dyr har den største hjerne blandt alle nulevende dyr målt i absolut vægt?", options: ["Kaskelothval", "Blåhval", "Elefant", "Menneske"], correct: "Kaskelothval", fact: "Hjernen kan veje op mod 7-8 kg." },
      { q: "Hvad kaldes videnskaben, der specifikt studerer dyrs adfærd?", options: ["Etologi", "Zoologi", "Biologi", "Økologi"], correct: "Etologi", fact: "Zoologi er den bredere videnskab om dyr generelt." },
    ],
  },
  sport: {
    nem: [
      { q: "Hvor mange spillere er der fra hvert hold på en fodboldbane samtidig (inkl. målmand)?", options: ["11", "9", "7", "13"], correct: "11", fact: "Det giver 22 spillere på banen i alt." },
      { q: "I hvilken by blev de første moderne olympiske lege afholdt i 1896?", options: ["Athen", "Paris", "London", "Rom"], correct: "Athen", fact: "Legene i 1896 havde deltagere fra 14 nationer." },
      { q: "Hvor mange ringe er der i det olympiske symbol?", options: ["5", "4", "6", "7"], correct: "5", fact: "Ringene symboliserer de fem beboede verdensdele." },
      { q: "Hvor langt er en maraton officielt?", options: ["42,195 km", "40 km", "45 km", "21,1 km"], correct: "42,195 km", fact: "Distancen stammer fra afstanden mellem Marathon og Athen." },
      { q: "Hvilket land har vundet flest VM-titler i mændenes fodbold?", options: ["Brasilien", "Tyskland", "Italien", "Argentina"], correct: "Brasilien", fact: "Brasilien er det eneste land, der har deltaget ved alle VM-slutrunder." },
      { q: "Hvor mange spillere er der på hvert hold i basketball på banen samtidig?", options: ["5", "6", "7", "4"], correct: "5", fact: "Et basketballhold kan dog have flere spillere på bænken." },
      { q: "Hvilken sport spiller man med en fjerbold, ofte kaldet en 'birdie'?", options: ["Badminton", "Tennis", "Squash", "Bordtennis"], correct: "Badminton", fact: "Fjerboldens fjer stammer traditionelt fra gåsevinger." },
      { q: "Hvor ofte afholdes VM i fodbold for mænd?", options: ["Hvert 4. år", "Hvert 2. år", "Hvert år", "Hvert 5. år"], correct: "Hvert 4. år", fact: "Turneringen har været afholdt siden 1930, med enkelte pauser under krigsårene." },
      { q: "Hvilken farve trøje bærer den samlede fører i Tour de France efter hver etape?", options: ["Gul", "Grøn", "Rød", "Blå"], correct: "Gul", fact: "Farven blev valgt, fordi det arrangerende avis 'L'Auto' var trykt på gult papir." },
      { q: "Hvor mange point får man normalt for et scoret mål i fodbold?", options: ["1", "2", "3", "0,5"], correct: "1", fact: "Målet tæller det samme, uanset hvor flot det er scoret." },
    ],
    mellem: [
      { q: "I hvilket engelsk grevskab blev sporten badminton kodificeret i sin moderne form, opkaldt efter et gods?", options: ["Gloucestershire", "Yorkshire", "Kent", "Surrey"], correct: "Gloucestershire", fact: "Navnet stammer fra Badminton House, hvor sporten blev kodificeret." },
      { q: "Hvor mange spillere er der på hvert hold på banen samtidig i håndbold (inkl. målmand)?", options: ["7", "6", "8", "5"], correct: "7", fact: "Det er 6 markspillere og 1 målmand." },
      { q: "Hvilken by var vært for OL i 1980, som blev boykottet af en lang række vestlige lande pga. Sovjetunionens invasion af Afghanistan?", options: ["Moskva", "Los Angeles", "Montreal", "Seoul"], correct: "Moskva", fact: "Over 60 lande deltog i boykotten." },
      { q: "Hvad hedder den skotske vintersport, hvor man skyder polerede stensten hen mod et mål på is?", options: ["Curling", "Bandy", "Ishockey", "Skeleton"], correct: "Curling", fact: "Sporten stammer oprindeligt fra Skotland." },
      { q: "Hvor mange sæt skal en herresingle-spiller vinde for at vinde en kamp ved Wimbledon (best of hvor mange)?", options: ["3 ud af 5", "2 ud af 3", "4 ud af 7", "1 ud af 1"], correct: "3 ud af 5", fact: "Kvinderækken spiller til gengæld normalt bedst af 3 sæt." },
      { q: "Hvilken sport spilles ved VM med en 'puck' i stedet for en bold?", options: ["Ishockey", "Bandy", "Curling", "Rugby"], correct: "Ishockey", fact: "Pucken er lavet af hårdt vulkaniseret gummi." },
      { q: "Hvor mange spillere er der på hvert hold i volleyball på banen samtidig?", options: ["6", "5", "7", "4"], correct: "6", fact: "Holdene bytter position med uret, hver gang de vinder retten til at serve." },
      { q: "Hvilket land vandt det allerførste VM i fodbold i 1930?", options: ["Uruguay", "Brasilien", "Argentina", "Italien"], correct: "Uruguay", fact: "Landet var også vært for selve turneringen." },
      { q: "Hvad kaldes det, når en bokser vinder en kamp ved at slå modstanderen ud?", options: ["Knockout", "Teknisk sejr", "Diskvalifikation", "Pointsejr"], correct: "Knockout", fact: "Forkortelsen 'KO' bruges ofte i stedet for det fulde ord." },
      { q: "Hvilken sport bruger udtrykkene 'birdie' og 'eagle' om scoring under par?", options: ["Golf", "Tennis", "Badminton", "Baseball"], correct: "Golf", fact: "'Eagle' betyder to slag under par på et hul." },
    ],
    svaer: [
      { q: "Hvornår vandt det danske herrehåndboldlandshold sit første OL-guld?", options: ["2016 (Rio)", "2012 (London)", "2008 (Beijing)", "2004 (Athen)"], correct: "2016 (Rio)", fact: "Holdet gentog bedriften ved både Tokyo 2020 og Paris 2024." },
      { q: "Hvilken by var oprindeligt tildelt værtskabet for OL 1940, men mistede det pga. 2. verdenskrig?", options: ["Tokyo", "Helsinki", "Berlin", "Rom"], correct: "Tokyo", fact: "Byen fik i stedet værtskabet for OL i 1964." },
      { q: "Hvor mange point er et field goal værd i basketball, hvis det skydes bagfra 3-punkts-linjen?", options: ["3", "2", "1", "4"], correct: "3", fact: "Reglen blev indført i NBA i 1979." },
      { q: "Hvilken sportsgren opfandt James Naismith i 1891 som en indendørs vinteraktivitet?", options: ["Basketball", "Volleyball", "Håndbold", "Badminton"], correct: "Basketball", fact: "Naismith brugte oprindeligt to frugtkurve som mål." },
      { q: "Hvor mange etaper består Tour de France normalt af?", options: ["21", "15", "25", "18"], correct: "21", fact: "Løbet strækker sig typisk over godt tre uger." },
      { q: "Hvilket land har vundet flest OL-guldmedaljer gennem tiden ved sommer-OL?", options: ["USA", "Sovjetunionen/Rusland", "Storbritannien", "Kina"], correct: "USA", fact: "USA har deltaget ved næsten alle sommer-OL siden 1896." },
      { q: "Hvor mange spillere må maksimalt være på isen samtidig for ét hold i ishockey (inkl. målmand)?", options: ["6", "5", "7", "4"], correct: "6", fact: "Det er 5 markspillere og 1 målmand." },
      { q: "Hvilken tennisspiller var den første til at vinde alle fire Grand Slam-turneringer i samme kalenderår i den moderne æra?", options: ["Rod Laver", "Roger Federer", "Novak Djokovic", "Björn Borg"], correct: "Rod Laver", fact: "Han er stadig den eneste mand, der har gjort det to gange." },
      { q: "Hvilken by var vært for de første OL, hvor kvinder fik lov at deltage, i 1900?", options: ["Paris", "Athen", "London", "St. Louis"], correct: "Paris", fact: "Kvinderne deltog dengang bl.a. i tennis og golf." },
      { q: "Hvad kaldes disciplinen i atletik, der kombinerer 10 forskellige øvelser fordelt over to dage?", options: ["Tikamp", "Femkamp", "Triatlon", "Moderne femkamp"], correct: "Tikamp", fact: "Vinderen kåres ofte uofficielt som verdens bedste atlet." },
    ],
  },
  alment: {
    nem: [
      { q: "Hvor mange knogler har et voksent menneske normalt?", options: ["206", "186", "226", "246"], correct: "206", fact: "Babyer fødes med omkring 300 knogler, som gror sammen." },
      { q: "Hvilket metal er flydende ved stuetemperatur?", options: ["Kviksølv", "Jern", "Guld", "Aluminium"], correct: "Kviksølv", fact: "Kviksølv er giftigt og bruges i dag langt sjældnere end tidligere." },
      { q: "Hvor mange planeter er der i vores solsystem, siden Pluto blev nedgraderet i 2006?", options: ["8", "9", "7", "10"], correct: "8", fact: "Pluto blev omklassificeret til en dværgplanet i 2006." },
      { q: "Hvilken dansk fysiker vandt Nobelprisen i fysik i 1922 for sit arbejde med atomets struktur?", options: ["Niels Bohr", "H.C. Ørsted", "Tycho Brahe", "Ole Rømer"], correct: "Niels Bohr", fact: "Han grundlagde senere Niels Bohr Institutet i København." },
      { q: "Hvad hedder den mindste enhed af et grundstof, der stadig har grundstoffets kemiske egenskaber?", options: ["Atom", "Molekyle", "Celle", "Elektron"], correct: "Atom", fact: "Ordet stammer fra græsk og betyder 'udelelig'." },
      { q: "Hvor mange dage er der i februar i et skudår?", options: ["29", "28", "30", "31"], correct: "29", fact: "Skudår sikrer, at kalenderen følger Jordens omløb om Solen præcist nok." },
      { q: "Hvilken farve fremkommer ved at blande rødt og hvidt?", options: ["Lyserød", "Orange", "Lilla", "Brun"], correct: "Lyserød", fact: "Jo mere hvidt, jo lysere bliver den lyserøde nuance." },
      { q: "Hvad kaldes vand i fast form?", options: ["Is", "Damp", "Sne", "Frost"], correct: "Is", fact: "Vand fryser til is ved 0 grader celsius ved normalt tryk." },
      { q: "Hvor mange sider har en trekant?", options: ["3", "4", "5", "6"], correct: "3", fact: "Det er den geometriske figur med færrest mulige sider." },
      { q: "Hvad kaldes det, når himlen bliver mørk, fordi solen går ned?", options: ["Solnedgang", "Solopgang", "Måneskin", "Skumring"], correct: "Solnedgang", fact: "Det modsatte fænomen om morgenen kaldes solopgang." },
    ],
    mellem: [
      { q: "Hvad er hovedstaden i Australien (ikke Sydney)?", options: ["Canberra", "Sydney", "Melbourne", "Perth"], correct: "Canberra", fact: "Byen blev grundlagt som kompromis mellem Sydney og Melbourne." },
      { q: "Hvor mange hjerteslag har et menneske i gennemsnit per minut i hvile?", options: ["60-100", "20-40", "150-200", "250-300"], correct: "60-100", fact: "Under hård træning kan pulsen stige til det dobbelte eller mere." },
      { q: "Hvem opfandt World Wide Web i 1989?", options: ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Alan Turing"], correct: "Tim Berners-Lee", fact: "Han arbejdede dengang på forskningscentret CERN." },
      { q: "Hvilken dansk astronom opdagede i 1676, at lyset har en endelig hastighed?", options: ["Ole Rømer", "Tycho Brahe", "Niels Bohr", "H.C. Ørsted"], correct: "Ole Rømer", fact: "Han beregnede lysets hastighed ud fra observationer af Jupiters måner." },
      { q: "Hvad kaldes læren om jordens klimasystemer og atmosfæriske fænomener?", options: ["Meteorologi", "Geologi", "Astronomi", "Oceanografi"], correct: "Meteorologi", fact: "Moderne meteorologi bruger bl.a. satellitter og supercomputere." },
      { q: "Hvor mange lande er der i verden ifølge FN's optælling af medlemslande?", options: ["193", "180", "200", "210"], correct: "193", fact: "Antallet kan diskuteres, da nogle territorier ikke er fuldt anerkendte." },
      { q: "Hvad kaldes det største organ i den menneskelige krop?", options: ["Huden", "Leveren", "Lungerne", "Hjernen"], correct: "Huden", fact: "Huden på en voksen dækker et areal på op mod 2 kvadratmeter." },
      { q: "Hvilket grundstof har det kemiske symbol 'O'?", options: ["Oxygen (ilt)", "Guld", "Jern", "Osmium"], correct: "Oxygen (ilt)", fact: "Guld har i stedet det kemiske symbol 'Au'." },
      { q: "Hvor mange tænder har et voksent menneske normalt, inkl. visdomstænder?", options: ["32", "28", "30", "34"], correct: "32", fact: "Mange får dog trukket en eller flere visdomstænder ud." },
      { q: "Hvad kaldes videnskaben om stjerner, planeter og resten af universet?", options: ["Astronomi", "Astrologi", "Geologi", "Meteorologi"], correct: "Astronomi", fact: "Astrologi, som ofte forveksles med det, er ikke en videnskab." },
    ],
    svaer: [
      { q: "Hvilket år opdagede den danske fysiker H.C. Ørsted elektromagnetismen?", options: ["1820", "1800", "1850", "1900"], correct: "1820", fact: "Opdagelsen skete angiveligt ved et tilfælde under en forelæsning." },
      { q: "Hvad hedder den kognitive bias, hvor man overvurderer sandsynligheden for begivenheder, man let kan huske eksempler på?", options: ["Tilgængelighedsheuristik", "Bekræftelsesbias", "Ankereffekt", "Dunning-Kruger-effekten"], correct: "Tilgængelighedsheuristik", fact: "Bias'en får fx flyulykker til at føles hyppigere, end de statistisk er." },
      { q: "Hvor mange kromosomer har en normal menneskelig kropscelle?", options: ["46", "23", "44", "48"], correct: "46", fact: "Det svarer til 23 par, ét fra hver forælder." },
      { q: "Hvilken trykenhed er opkaldt efter den italienske fysiker Evangelista Torricelli?", options: ["Torr", "Pascal", "Bar", "Atmosfære"], correct: "Torr", fact: "760 torr svarer til normalt lufttryk ved havoverfladen." },
      { q: "Hvad hedder tallet, der angiver forholdet mellem en cirkels omkreds og diameter (ca. 3,14159)?", options: ["Pi (π)", "Phi (φ)", "Eulers tal (e)", "Tau (τ)"], correct: "Pi (π)", fact: "Tallet har uendeligt mange decimaler uden gentaget mønster." },
      { q: "Hvilket grundstof har det højeste smeltepunkt af alle grundstoffer?", options: ["Wolfram", "Jern", "Titan", "Platin"], correct: "Wolfram", fact: "Smeltepunktet ligger på over 3.400 grader celsius." },
      { q: "Hvad kaldes Albert Einsteins berømte teori om, at tid og rum er forbundne og relative?", options: ["Relativitetsteorien", "Kvantemekanik", "Strengteori", "Termodynamik"], correct: "Relativitetsteorien", fact: "Teorien findes i to dele: den specielle og den generelle." },
      { q: "Cirka hvor mange knogler har et nyfødt barn, før nogle af dem gror sammen?", options: ["Ca. 300", "Ca. 206", "Ca. 150", "Ca. 400"], correct: "Ca. 300", fact: "Mange af knoglerne smelter sammen i løbet af barndommen." },
      { q: "Hvad hedder den mindste bestanddel af et atom, der bærer negativ elektrisk ladning?", options: ["Elektron", "Proton", "Neutron", "Kvark"], correct: "Elektron", fact: "Protoner har til sammenligning positiv ladning." },
      { q: "Hvilken dansk filosof er kendt for begrebet 'Angestens Begreb' og regnes som eksistentialismens far?", options: ["Søren Kierkegaard", "Niels Bohr", "H.C. Andersen", "N.F.S. Grundtvig"], correct: "Søren Kierkegaard", fact: "Han skrev store dele af sit forfatterskab under forskellige pseudonymer." },
    ],
  },
  influencer: {
    nem: [
      { q: "Hvilket TV-program gjorde Silas Holst berømt som professionel danser?", options: ["Vild med Dans", "X Factor", "Voice", "Paradise Hotel"], correct: "Vild med Dans", fact: "Han har vundet programmet hele tre gange som professionel danser." },
      { q: "Hvilken dansk sanger er kendt for hittet 'Told You So' fra 2014?", options: ["Christopher", "Rasmus Seebach", "Basim", "Lukas Graham"], correct: "Christopher", fact: "Sangen nåede op som nummer 4 på den danske hitliste." },
      { q: "Hvilken by er TikTok-stjernen Zawadi Kristina kendt for at optræde i, i sine dansevideoer?", options: ["København", "Aarhus", "Odense", "Aalborg"], correct: "København", fact: "Hun er kendt for at blande afro-diasporisk mode med skandinavisk stil." },
      { q: "Hvilket verdenskendt undertøjsmærke har den danske model Josephine Skriver optrådt fast for siden 2015?", options: ["Victoria's Secret", "Calvin Klein", "H&M", "Chanel"], correct: "Victoria's Secret", fact: "Hun har gået med på catwalken ved deres store modeshow hvert år siden." },
      { q: "Hvad er TikTokeren Yespar især kendt for at lave videoer om?", options: ["Sjove sketches og udfordringer", "Nyhedsanalyser", "Madlavningstutorials", "Boganmeldelser"], correct: "Sjove sketches og udfordringer", fact: "Han slog for alvor igennem omkring 2020." },
      { q: "Hvad hedder sangeren Christopher til fulde navn?", options: ["Christopher Lund Nissen", "Christopher Larsen", "Christopher Holm", "Christopher Berg"], correct: "Christopher Lund Nissen", fact: "Han er født i København i januar 1992." },
      { q: "Hvor gammel var Josephine Skriver, da hun blev opdaget som model under en rejse til New York?", options: ["15 år", "12 år", "18 år", "21 år"], correct: "15 år", fact: "Hun var i New York med sit fodboldhold, da hun blev opdaget." },
      { q: "I hvilken by er Gustav Salinas født?", options: ["Aarhus", "København", "Odense", "Aalborg"], correct: "Aarhus", fact: "Han voksede primært op i Santiago, Chile, med sin danske far og chilenske mor." },
      { q: "I hvilket år gjorde Silas Holst sin professionelle debut som danser i 'Vild med dans'?", options: ["2008", "2005", "2011", "2014"], correct: "2008", fact: "Han har danset, siden han var to år gammel." },
      { q: "Hvilket år startede Anders Hemmingsen sin nu meget populære meme-side på Instagram?", options: ["2015", "2010", "2018", "2020"], correct: "2015", fact: "Målet var at skabe et lokalt dansk meme-fællesskab." },
    ],
    mellem: [
      { q: "Hvilket dansk realityprogram blev Gustav Salinas oprindeligt kendt fra som 18-årig i 2008?", options: ["Dagens Mand", "Paradise Hotel", "Ex on the Beach", "Bachelor"], correct: "Dagens Mand", fact: "I dag laver han i stedet indhold om træning og forretning." },
      { q: "Hvad hedder de to virksomheder, Gustav Salinas driver ved siden af sit indhold i dag?", options: ["FitnessNu og Salinas Slik", "Matas og Netto", "Zalando og H&M", "Lego og Bestseller"], correct: "FitnessNu og Salinas Slik", fact: "Den ene handler om træning, den anden om slik." },
      { q: "Hvad er Anders Hemmingsen især kendt for at drive på Instagram?", options: ["Danmarks mest fulgte meme-side", "En nyhedskanal", "En boligblog", "En rejseblog"], correct: "Danmarks mest fulgte meme-side", fact: "Siden deler humoristisk indhold, som ofte bliver delt videre af følgerne." },
      { q: "Hvilke to modemærker har TikTokeren Zawadi Kristina bl.a. lavet reklamesamarbejder med?", options: ["Zalando og H&M", "Nike og Adidas", "Lego og Netto", "Apple og Samsung"], correct: "Zalando og H&M", fact: "Den slags samarbejder er en vigtig indtægtskilde for mange influencere." },
      { q: "Hvilken hæderspris fik Christopher i 2013 for sin store tilstedeværelse på det sociale medie Instagram?", options: ["Årets Instagrammer", "Årets YouTuber", "Årets Podcaster", "Årets Blogger"], correct: "Årets Instagrammer", fact: "Prisen blev uddelt af The Voice." },
      { q: "Hvilket dansk modelbureau blev Josephine Skriver oprindeligt tilknyttet, da hun startede sin karriere?", options: ["Unique Models", "Elite Models", "IMG Models", "Scoop Models"], correct: "Unique Models", fact: "Bureauet er baseret i København." },
      { q: "Hvad hed Christophers debutalbum fra 2012?", options: ["Colours", "Told You So", "Closer", "Under the Surface"], correct: "Colours", fact: "'Told You So' udkom to år senere, i 2014." },
      { q: "I hvilket land voksede Gustav Salinas primært op, før han flyttede til København som niårig?", options: ["Chile", "Spanien", "Argentina", "Mexico"], correct: "Chile", fact: "Hans mor er chilensk, og familien boede i landets hovedstad Santiago." },
      { q: "Hvilke to mærker har TikTokeren Yespar bl.a. lavet reklamesamarbejder med?", options: ["Fanta og Wolt", "Coca-Cola og Just Eat", "Carlsberg og Nemlig.com", "Pepsi og Foodora"], correct: "Fanta og Wolt", fact: "Han er tilknyttet bureauet Eighteen Agency for den slags samarbejder." },
      { q: "Hvor arbejdede Anders Hemmingsen, inden han startede sin meme-side, uden nogen kommunikationsuddannelse?", options: ["DR (Danmarks Radio)", "TV 2", "Berlingske", "Politiken"], correct: "DR (Danmarks Radio)", fact: "Han arbejdede i DR's økonomiafdeling, da siden startede som en hobby." },
    ],
    svaer: [
      { q: "I hvilket år blev Silas Holst den første professionelle danser i 'Vild med dans' til at vinde med en partner af samme køn?", options: ["2019", "2015", "2021", "2011"], correct: "2019", fact: "Han vandt sammen med skuespiller Jakob Fauerby." },
      { q: "Hvor mange gange har Silas Holst i alt vundet 'Vild med dans' som professionel danser?", options: ["3 gange", "1 gang", "5 gange", "2 gange"], correct: "3 gange", fact: "Det gør ham til en af de mest vindende professionelle dansere i programmets historie." },
      { q: "Hvad hedder Gustav Salinas' tidligere kæreste, som han stadig driver virksomheden Salinas Slik sammen med?", options: ["Mulle", "Frederik", "Kevin", "Anders"], correct: "Mulle", fact: "De fortsatte som forretningspartnere, selvom parforholdet sluttede i 2023." },
      { q: "Hvilket bureau er TikTokeren Yespar tilknyttet for professionelle samarbejder?", options: ["Eighteen Agency", "United Influencers", "Talent Nation", "Zenith Media"], correct: "Eighteen Agency", fact: "Bureauer som dette matcher influencere med brands, der ønsker reklamesamarbejder." },
      { q: "I hvilket årti fik Christopher sit store gennembrud som popsanger i Danmark?", options: ["2010'erne", "1990'erne", "2000'erne", "2020'erne"], correct: "2010'erne", fact: "Albummet 'Told You So' udkom i 2014." },
      { q: "Hvilken anden professionel danser deler rekorden for flest sejre i 'Vild med dans' med Silas Holst?", options: ["Thomas Evers Poulsen", "Jenna Bagge", "Karina Frimodt", "Mads Vad"], correct: "Thomas Evers Poulsen", fact: "Begge har vundet programmet tre gange som professionelle dansere." },
      { q: "Hvilket år udkom Christophers album 'Closer'?", options: ["2016", "2014", "2018", "2020"], correct: "2016", fact: "Han har udgivet fem album i alt siden sit gennembrud." },
      { q: "Ud over dans er Silas Holst også uddannet inden for hvilket felt?", options: ["Skuespil", "Sang", "Musikproduktion", "Koreografi"], correct: "Skuespil", fact: "Han er også uddannet danselærer fra De Danske Danseskoler." },
      { q: "For hvilke to modehuse debuterede Josephine Skriver på catwalken ved New York Fashion Week i 2011?", options: ["Calvin Klein og Rag & Bone", "Chanel og Dior", "Gucci og Prada", "Versace og Armani"], correct: "Calvin Klein og Rag & Bone", fact: "Hun gik senere også for Chanel, Dior og Yves Saint Laurent." },
      { q: "Hvilket år blev Josephine Skriver officielt udnævnt til Victoria's Secret 'Angel'?", options: ["2016", "2013", "2018", "2011"], correct: "2016", fact: "Hun havde da allerede gået med i showet i et par år." },
    ],
  },
};
